/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `City`;

CREATE TABLE `City` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `pos_x` INT NOT NULL,
  `pos_y` INT NOT NULL)
 ENGINE=InnoDB;

