Trade App: NoiseFunc Class Reference
NoiseFunc Class Reference
Noise Function Based on Perlin Noise.
#include "NoiseFunc.hpp"
Public Member Functions
NoiseFunc ()
NoiseFunc (std::stringstream *ss)
NoiseFunc (float gridPeriod)
void fromStringStream (std::stringstream *ss)
void toStringStream (std::stringstream *ss)
float getRaw (float x, float y)
Get the return of this noise function not modified by gridPeriod.
float get (int x, int y)
Get the return of this noise function modified by gridPeriod.
Private Member Functions
float perlin (float x, float y)
float dotGridGradient (int ix, int iy, float x, float y)
float lerp (float a0, float a1, float w=0.5)
void addGridGradient (int x, int y)
float newRand ()
std::pair< float, float > newRandPair ()
Private Attributes
float gridPeriod
std::vector< std::vector< std::pair< float, float > > > Grid
Static Private Attributes
static const unsigned int rand_steps = 2048
Detailed Description
Noise Function Based on Perlin Noise.
Definition at line 12 of file NoiseFunc.hpp.
Constructor & Destructor Documentation
NoiseFunc::NoiseFunc ()
Definition at line 3 of file NoiseFunc.cpp.
References Grid, gridPeriod, and newRandPair().
NoiseFunc::NoiseFunc (std::stringstream * ss)
Definition at line 21 of file NoiseFunc.cpp.
References fromStringStream().
NoiseFunc::NoiseFunc (float gridPeriod)
Definition at line 12 of file NoiseFunc.cpp.
References Grid, gridPeriod, and newRandPair().
Member Function Documentation
void NoiseFunc::addGridGradient (int x, int y) private
Definition at line 104 of file NoiseFunc.cpp.
References Grid, and newRandPair().
Referenced by dotGridGradient().
float NoiseFunc::dotGridGradient (int ix, int iy, float x, float y) private
Definition at line 89 of file NoiseFunc.cpp.
References addGridGradient(), and Grid.
Referenced by perlin().
void NoiseFunc::fromStringStream (std::stringstream * ss)
Definition at line 26 of file NoiseFunc.cpp.
References Grid, and gridPeriod.
Referenced by NoiseFunc().
float NoiseFunc::get (int x, int y)
Get the return of this noise function modified by gridPeriod.
Parameters
float x x position in grid to get noise at
float y y position in grid to get noise at
Definition at line 59 of file NoiseFunc.cpp.
References gridPeriod, and perlin().
Referenced by WorldChunk::generateChunk().
float NoiseFunc::getRaw (float x, float y)
Get the return of this noise function not modified by gridPeriod.
Parameters
float x x position in grid to get noise at
float y y position in grid to get noise at
Definition at line 54 of file NoiseFunc.cpp.
References perlin().
float NoiseFunc::lerp (float a0, float a1, float w = 0.5) private
Definition at line 99 of file NoiseFunc.cpp.
Referenced by perlin().
float NoiseFunc::newRand () private
Definition at line 126 of file NoiseFunc.cpp.
References rand_steps.
Referenced by newRandPair().
std::pair< float, float > NoiseFunc::newRandPair () private
Definition at line 131 of file NoiseFunc.cpp.
References newRand().
Referenced by addGridGradient(), and NoiseFunc().
float NoiseFunc::perlin (float x, float y) private
Definition at line 64 of file NoiseFunc.cpp.
References dotGridGradient(), and lerp().
Referenced by get(), and getRaw().
void NoiseFunc::toStringStream (std::stringstream * ss)
Definition at line 40 of file NoiseFunc.cpp.
References Grid, and gridPeriod.
Member Data Documentation
std::vector< std::vector< std::pair< float, float > > > NoiseFunc::Grid private
Definition at line 50 of file NoiseFunc.hpp.
Referenced by addGridGradient(), dotGridGradient(), fromStringStream(), NoiseFunc(), and toStringStream().
float NoiseFunc::gridPeriod private
Definition at line 49 of file NoiseFunc.hpp.
Referenced by fromStringStream(), get(), NoiseFunc(), and toStringStream().
const unsigned int NoiseFunc::rand_steps = 2048 static private
Definition at line 38 of file NoiseFunc.hpp.
Referenced by newRand().
The documentation for this class was generated from the following files:
NoiseFunc.hpp
NoiseFunc.cpp