Arbitrage Simulator: Logger Class Reference
Logger Class Reference abstract
#include "Logger.hpp"
Public Types
enum LogLevel {
NONE = 0, DEBUG = 1, INFO = 2, WARN = 3,
ERROR = 4
}
Public Member Functions
virtual ~Logger ()
virtual void debug (const char *fmt,...)=0
virtual void info (const char *fmt,...)=0
virtual void warn (const char *fmt,...)=0
virtual void error (const char *fmt,...)=0
virtual void log (Logger::LogLevel level, const char *fmt,...)=0
Static Public Member Functions
static void configure ()
Protected Member Functions
virtual std::string format_string (LogLevel level, const char *fmt, va_list args)
std::string get_time ()
Static Protected Attributes
static const std::string levelStrings [4]
static int logLevel = 0
Detailed Description
Definition at line 12 of file Logger.hpp.
Member Enumeration Documentation
enum Logger::LogLevel
Enumerator
NONE
DEBUG
INFO
WARN
ERROR
Definition at line 15 of file Logger.hpp.
Constructor & Destructor Documentation
virtual Logger::~Logger () inline virtual
Definition at line 24 of file Logger.hpp.
References configure(), debug(), error(), info(), log(), and warn().
Member Function Documentation
void Logger::configure () static
Definition at line 12 of file Logger.cpp.
References ConfigLoader::getIntOption(), logLevel, and WARN.
Referenced by Game::configure(), and ~Logger().
virtual void Logger::debug (const char * fmt, ...) pure virtual
Implemented in BufferLogger, and ConsoleLogger.
Referenced by Game::run(), and ~Logger().
virtual void Logger::error (const char * fmt, ...) pure virtual
Implemented in BufferLogger, and ConsoleLogger.
Referenced by ~Logger().
std::string Logger::format_string (LogLevel level, const char * fmt, va_list args) protected virtual
Definition at line 21 of file Logger.cpp.
References get_time(), and levelStrings.
Referenced by BufferLogger::addToBuffer(), and ConsoleLogger::print().
std::string Logger::get_time () protected
Definition at line 36 of file Logger.cpp.
Referenced by format_string().
virtual void Logger::info (const char * fmt, ...) pure virtual
Implemented in BufferLogger, and ConsoleLogger.
Referenced by Game::run(), and ~Logger().
virtual void Logger::log (Logger::LogLevel level, const char * fmt, ...) pure virtual
Implemented in BufferLogger, and ConsoleLogger.
Referenced by ~Logger().
virtual void Logger::warn (const char * fmt, ...) pure virtual
Implemented in BufferLogger, and ConsoleLogger.
Referenced by ~Logger().
Member Data Documentation
const std::string Logger::levelStrings static protected
Initial value:
= {
    "DEBUG",
    "INFO",
    "WARNING",
    "ERROR"
}
Definition at line 33 of file Logger.hpp.
Referenced by format_string().
int Logger::logLevel = 0 static protected
Definition at line 34 of file Logger.hpp.
Referenced by BufferLogger::addToBuffer(), configure(), and ConsoleLogger::print().
The documentation for this class was generated from the following files:
Logger.hpp
Logger.cpp