Trade App: ServerSession Class Reference
ServerSession Class Reference
Server Session.
#include "ServerSession.hpp"
Public Types
enum REQUST_TYPE {
ERROR = 0, VERSION_CHECK = 1, VERSION_CHECK_OK = 2, VERSION_INCOMPATIBLE = 3,
LOGIN = 10, REQUEST_CHARACTER = 100, REQUEST_WORLD = 110, REQUEST_CHUNK = 120,
REQUEST_CITY = 130
}
Request Type.
enum SESSION_STATE {
UNSET = 5, HANDSHAKING = 10, AUTHENTICATING = 20, PLAYING = 30,
DISCONNECTING = 40, DISCONNECTED = 41
}
Public Member Functions
ServerSession ()
ServerSession (Connection conn)
int init (std::string version)
int run ()
Launch thread to manage this session.
bool write (std::string msg)
Wrapper for connection write.
void setConnection (Connection conn)
SESSION_STATE getState ()
Private Member Functions
void sessionLoop ()
Static Private Member Functions
static std::string VersionCheckHandler (ServerSession &myself, std::string msg)
Request Handler: Version Check.
static std::string LoginHandler (ServerSession &myself, std::string msg)
Request Handler: Login Handler Check for existing user with same username and password, if match then this session may use that users character.
Private Attributes
SESSION_STATE state
std::string version
std::thread thread
Connection conn
Static Private Attributes
static std::map< int, std::string(*)(ServerSession &myself, std::string msg)> requestMap
Request Handlers.
Detailed Description
Server Session.
Manager for server/client communication.
Definition at line 19 of file ServerSession.hpp.
Member Enumeration Documentation
enum ServerSession::REQUST_TYPE
Request Type.
An enumeration of all possible requests a client can make, or responses a server can return.
Enumerator
ERROR
VERSION_CHECK
VERSION_CHECK_OK
VERSION_INCOMPATIBLE
LOGIN
REQUEST_CHARACTER
REQUEST_WORLD
REQUEST_CHUNK
REQUEST_CITY
Definition at line 28 of file ServerSession.hpp.
                      {
         ERROR = 0,
         VERSION_CHECK = 1,
         VERSION_CHECK_OK = 2,
         VERSION_INCOMPATIBLE = 3,
         LOGIN = 10,
         REQUEST_CHARACTER = 100,
         REQUEST_WORLD = 110,
         REQUEST_CHUNK = 120,
         REQUEST_CITY = 130,
     };
enum ServerSession::SESSION_STATE
Enumerator
UNSET
HANDSHAKING
AUTHENTICATING
PLAYING
DISCONNECTING
DISCONNECTED
Definition at line 40 of file ServerSession.hpp.
{
         UNSET = 5,
         HANDSHAKING = 10,
         AUTHENTICATING = 20,
         PLAYING = 30,
         DISCONNECTING = 40,
         DISCONNECTED = 41
     };
Constructor & Destructor Documentation
ServerSession::ServerSession ()
Definition at line 9 of file ServerSession.cpp.
References state, UNSET, and version.
 {
     this->state = UNSET;
     this->version = "";
 }
ServerSession::ServerSession (Connection conn)
Definition at line 15 of file ServerSession.cpp.
References setConnection(), state, UNSET, and version.
 {
     this->state = UNSET;
     this->version = "";
     this->setConnection(conn);
 }
Member Function Documentation
ServerSession::SESSION_STATE ServerSession::getState ()
Definition at line 37 of file ServerSession.cpp.
References state.
 {
     return this->state;
 }
int ServerSession::init (std::string version)
Definition at line 22 of file ServerSession.cpp.
References version.
Referenced by Server::run().
 {
     this->version = version;
 }
std::string ServerSession::LoginHandler (ServerSession & myself, std::string msg) static private
Request Handler: Login Handler Check for existing user with same username and password, if match then this session may use that users character.
Otherwise, deny access.
Parameters
ServerSession &myself
std::string msg the message the client sent
Returns
std::string the response
Definition at line 101 of file ServerSession.cpp.
 {
     int type;
     std::string username, password;
     std::stringstream ss;
     ss.str(msg);
     ss>>type>>username>>password;
     return "Welcome, " + username;
 }
int ServerSession::run ()
Launch thread to manage this session.
Definition at line 27 of file ServerSession.cpp.
References sessionLoop(), and thread.
Referenced by Server::run().
 {
     this->thread = std::thread(&ServerSession::sessionLoop, this);
 }
void ServerSession::sessionLoop () private
Definition at line 42 of file ServerSession.cpp.
References Connection::close(), conn, DISCONNECTED, DISCONNECTING, ERROR, HANDSHAKING, Connection::read(), requestMap, state, and Connection::write().
Referenced by run().
 {
     this->state = HANDSHAKING;
     while (true) {
         try {
             std::string message = this->conn.read();
             std::cout<<message<<std::endl;
             std::stringstream ss;
             int request_type;
             ss.str(message);
             ss>>request_type;
             std::string response = boost::lexical_cast<std::string>(ERROR) + " invalid message";
             if (this->requestMap.find(request_type) != this->requestMap.end()) {
                 response = this->requestMap[request_type](*this, message);
             }
             std::cout<<response;
             this->conn.write(response);
             if (state == DISCONNECTING) {
                 this->conn.close();
                 this->state = DISCONNECTED;
                 return;
             }
         } catch(std::exception& e) {
             std::cerr<<e.what()<<std::endl;
             this->conn.close();
             this->state = DISCONNECTED;
             return;
         }
     }
 }
void ServerSession::setConnection (Connection conn)
Definition at line 32 of file ServerSession.cpp.
References conn.
Referenced by ServerSession().
 {
     this->conn = conn;
 }
std::string ServerSession::VersionCheckHandler (ServerSession & myself, std::string msg) static private
Request Handler: Version Check.
Handle a request to check the compatibility of this server and a client.
Parameters
ServerSession &myself
std::string msg the message the client sent
Returns
std::string the response
Definition at line 78 of file ServerSession.cpp.
References AUTHENTICATING, DISCONNECTING, state, version, VERSION_CHECK_OK, and VERSION_INCOMPATIBLE.
 {
     int type;
     std::string version;
     std::stringstream ss;
     ss.str(msg);
     ss>>type>>version;
     std::cout<<"Client request version check ";
     if (myself.version == version) {
         std::cout<<"version OK\n";
         myself.state = AUTHENTICATING; // continue to next state
         return boost::lexical_cast<std::string>(ServerSession::VERSION_CHECK_OK) + "\n";
     } else {
         std::cout<<"version INCOMPATIBLE\n";
         myself.state = DISCONNECTING; // flag to disconnect
         return boost::lexical_cast<std::string>(ServerSession::VERSION_INCOMPATIBLE) +
             " " +
             myself.version +
             "\n"
         ;
     }
 }
bool ServerSession::write (std::string msg)
Wrapper for connection write.
Allow for owner to write direcly to this connection.
Parameters
std::string msg
Returns
bool success
Member Data Documentation
Connection ServerSession::conn private
Definition at line 74 of file ServerSession.hpp.
Referenced by sessionLoop(), and setConnection().
std::map< int, std::string(*)(ServerSession &myself, std::string msg)> ServerSession::requestMap static private
Initial value:
=
    {
        {ServerSession::VERSION_CHECK, VersionCheckHandler},
        {ServerSession::LOGIN, LoginHandler}
    }
Request Handlers.
All handlers will take a string message and return a string response
Definition at line 82 of file ServerSession.hpp.
Referenced by sessionLoop().
SESSION_STATE ServerSession::state private
Definition at line 71 of file ServerSession.hpp.
Referenced by getState(), ServerSession(), sessionLoop(), and VersionCheckHandler().
std::thread ServerSession::thread private
Definition at line 73 of file ServerSession.hpp.
Referenced by run().
std::string ServerSession::version private
Definition at line 72 of file ServerSession.hpp.
Referenced by init(), ServerSession(), and VersionCheckHandler().
The documentation for this class was generated from the following files:
ServerSession.hpp
ServerSession.cpp