Trade App: GameWindow Class Reference
GameWindow Class Reference
GameWindow.
#include "GameWindow.hpp"
Public Member Functions
GameWindow ()
virtual ~GameWindow ()
virtual void init ()
virtual void resize (int height, int width)
virtual void put (unsigned int colorPair, unsigned int layer, char c, int y, int x)
virtual void put (Window::TextElement c, int y, int x)
virtual void clear ()
virtual void render ()
Public Member Functions inherited from CursesWindow
CursesWindow ()
CursesWindow (int y, int x, int height, int width)
virtual ~CursesWindow ()
virtual void putstr (int y, int x, std::string str)
virtual void move (int y, int x)
virtual int getCh ()
virtual int getY ()
virtual int getX ()
virtual int getHeight ()
virtual int getWidth ()
Public Member Functions inherited from Window
virtual ~Window ()
Private Attributes
std::vector< std::vector< Window::TextElement > > ScreenBuffer
Additional Inherited Members
Public Types inherited from CursesWindow
typedef boost::shared_ptr< Window > window_ptr
Public Types inherited from Window
typedef boost::shared_ptr< Window > window_ptr
Protected Attributes inherited from CursesWindow
WINDOW * win
int y
int x
int height
int width
Detailed Description
GameWindow.
Buffer and Curses window for a displaying game world
Definition at line 14 of file GameWindow.hpp.
Constructor & Destructor Documentation
GameWindow::GameWindow ()
Definition at line 3 of file GameWindow.cpp.
GameWindow::~GameWindow () virtual
Definition at line 7 of file GameWindow.cpp.
Member Function Documentation
void GameWindow::clear () virtual
Reimplemented from CursesWindow.
Definition at line 52 of file GameWindow.cpp.
References Window::TextElement::c, Window::TextElement::colorPair, Window::TextElement::layer, and ScreenBuffer.
void GameWindow::init () virtual
Reimplemented from CursesWindow.
Definition at line 11 of file GameWindow.cpp.
References CursesWindow::init(), and resize().
void GameWindow::put (unsigned int colorPair, unsigned int layer, char c, int y, int x) virtual
Reimplemented from CursesWindow.
Definition at line 34 of file GameWindow.cpp.
References Window::TextElement::c, Window::TextElement::colorPair, and Window::TextElement::layer.
void GameWindow::put (Window::TextElement c, int y, int x) virtual
Reimplemented from CursesWindow.
Definition at line 43 of file GameWindow.cpp.
References Window::TextElement::layer, ScreenBuffer, CursesWindow::x, and CursesWindow::y.
void GameWindow::render () virtual
Reimplemented from CursesWindow.
Definition at line 67 of file GameWindow.cpp.
References CursesWindow::render(), ScreenBuffer, and CursesWindow::win.
void GameWindow::resize (int height, int width) virtual
Reimplemented from CursesWindow.
Definition at line 17 of file GameWindow.cpp.
References Window::TextElement::c, Window::TextElement::colorPair, CursesWindow::height, Window::TextElement::layer, CursesWindow::resize(), ScreenBuffer, and CursesWindow::width.
Referenced by init().
Member Data Documentation
std::vector< std::vector< Window::TextElement > > GameWindow::ScreenBuffer private
Definition at line 31 of file GameWindow.hpp.
Referenced by clear(), put(), render(), and resize().
The documentation for this class was generated from the following files:
GameWindow.hpp
GameWindow.cpp