Arbitrage Simulator: Item Class Reference
Item Class Reference
Item.
#include "Item.hpp"
Public Member Functions
Item ()
Item (int id, std::string name, std::string description, int weight, float baseWorth)
Item (std::stringstream *ss)
void fromStringStream (std::stringstream *ss)
From String Stream.
void toStringStream (std::stringstream *ss)
To String Stream.
int getId ()
std::string getName ()
std::string getDescription ()
int getWeight ()
float getBaseWorth ()
Private Attributes
int id
std::string name
std::string description
int weight
float baseWorth
Detailed Description
Item.
Any item which may be bought/sold/equipped in game.
id must be unique as this will be a flyweight class, and inventories will only hold ids to this class. -1 signifies an uninitialized id, and will not be added to the ItemContainer
Definition at line 18 of file Item.hpp.
Constructor & Destructor Documentation
Item::Item ()
Definition at line 3 of file Item.cpp.
References baseWorth, description, name, and weight.
Item::Item (int id, std::string name, std::string description, int weight, float baseWorth)
Definition at line 12 of file Item.cpp.
References baseWorth, description, id, name, and weight.
Item::Item (std::stringstream * ss)
Definition at line 21 of file Item.cpp.
References fromStringStream().
Member Function Documentation
void Item::fromStringStream (std::stringstream * ss) virtual
From String Stream.
Assume this object is the next object in the stringstream and restore it's own state based on the stringstream's contents.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 26 of file Item.cpp.
References baseWorth, description, Globals::file_delimiter, id, name, Globals::object_delimiter, and weight.
Referenced by Item().
float Item::getBaseWorth ()
Definition at line 80 of file Item.cpp.
References baseWorth.
Referenced by GameState::CityInventory::getCityInventory(), and ItemMap::init().
std::string Item::getDescription ()
Definition at line 70 of file Item.cpp.
References description.
Referenced by GameState::CityInventory::getCityInventory(), and ItemMap::init().
int Item::getId ()
Definition at line 60 of file Item.cpp.
References id.
Referenced by Inventory::add(), and ItemMap::init().
std::string Item::getName ()
Definition at line 65 of file Item.cpp.
References name.
Referenced by GameState::CityInventory::getCityInventory(), and ItemMap::init().
int Item::getWeight ()
Definition at line 75 of file Item.cpp.
References weight.
Referenced by GameState::CityInventory::getCityInventory(), and ItemMap::init().
void Item::toStringStream (std::stringstream * ss) virtual
To String Stream.
Add this object's state into the stringstream at the current point in the stream.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 52 of file Item.cpp.
References description, Globals::file_delimiter, name, Globals::object_delimiter, and weight.
Member Data Documentation
float Item::baseWorth private
Definition at line 38 of file Item.hpp.
Referenced by fromStringStream(), getBaseWorth(), and Item().
std::string Item::description private
Definition at line 36 of file Item.hpp.
Referenced by fromStringStream(), getDescription(), Item(), and toStringStream().
int Item::id private
Definition at line 34 of file Item.hpp.
Referenced by fromStringStream(), getId(), and Item().
std::string Item::name private
Definition at line 35 of file Item.hpp.
Referenced by fromStringStream(), getName(), Item(), and toStringStream().
int Item::weight private
Definition at line 37 of file Item.hpp.
Referenced by fromStringStream(), getWeight(), Item(), and toStringStream().
The documentation for this class was generated from the following files:
Item.hpp
Item.cpp