Arbitrage Simulator: GameState::Playing Class Reference
GameState::Playing Class Reference
#include "Playing.hpp"
Public Member Functions
void init ()
void update (WorldInteractionInterface *worldProxy, Context *ctx)
void render (WorldInteractionInterface *worldProxy, Window::window_ptr window)
State * nextState ()
void clearNextState ()
bool shouldClose ()
Public Member Functions inherited from GameState::State
virtual void setLogger (Logger::LoggerPtr logger)
virtual int passDown ()
virtual int passUp ()
virtual void recvDown (int msg)
virtual void recvUp (int msg)
Private Attributes
Player player
Camera camera
GameState::State * newState
Additional Inherited Members
Protected Attributes inherited from GameState::State
Logger::LoggerPtr logger
int msgDown
int msgUp
int recvMsgDown
int recvMsgUp
Detailed Description
Definition at line 19 of file Playing.hpp.
Member Function Documentation
void GameState::Playing::clearNextState () virtual
Implements GameState::State.
Definition at line 76 of file Playing.cpp.
References newState.
void GameState::Playing::init () virtual
Implements GameState::State.
Definition at line 3 of file Playing.cpp.
References camera, GameState::State::logger, and player.
GameState::State * GameState::Playing::nextState () virtual
Implements GameState::State.
Definition at line 71 of file Playing.cpp.
References newState.
void GameState::Playing::render (WorldInteractionInterface * worldProxy, Window::window_ptr window) virtual
Implements GameState::State.
Definition at line 56 of file Playing.cpp.
References camera, Player::getYX(), WorldInteractionInterface::movePlayerToCoordinate(), Camera::moveTo(), player, and Camera::render().
bool GameState::Playing::shouldClose () virtual
Implements GameState::State.
Definition at line 81 of file Playing.cpp.
void GameState::Playing::update (WorldInteractionInterface * worldProxy, Context * ctx) virtual
Implements GameState::State.
Definition at line 10 of file Playing.cpp.
References GameState::Menu::addOption(), BACK, Tile::CITIES, DOWN, WorldInteractionInterface::getCity(), Tile::getElevation(), City::getName(), WorldInteractionInterface::getTileUnderPlayer(), Tile::getType(), Player::getYX(), GameState::Menu::init(), GameState::CityInventory::init(), Context::input, LEFT, GameState::State::logger, Player::move(), WorldInteractionInterface::movePlayerToCoordinate(), newState, player, GameState::State::recvMsgUp, RIGHT, GameState::CityInventory::setCity(), and UP.
Member Data Documentation
Camera GameState::Playing::camera private
Definition at line 30 of file Playing.hpp.
Referenced by init(), and render().
GameState::State* GameState::Playing::newState private
Definition at line 31 of file Playing.hpp.
Referenced by clearNextState(), nextState(), and update().
Player GameState::Playing::player private
Definition at line 29 of file Playing.hpp.
Referenced by init(), render(), and update().
The documentation for this class was generated from the following files:
Playing.hpp
Playing.cpp