Trade App: ConfigLoader Class Reference
ConfigLoader Class Reference
Configuration Loader.
#include "ConfigLoader.hpp"
Static Public Member Functions
static void load ()
static void save ()
static std::string getVersion ()
static int getIntOption (std::string key, int defaultTo=-1)
static std::string getStringOption (std::string key, std::string defaultTo="")
static void mutateOption (std::string key, int value)
static void mutateOption (std::string key, std::string value)
static std::vector< std::pair< std::string, std::string > > getAllOptions ()
Private Types
using c_iter = std::map< std::string, std::string >::const_iterator
Private Member Functions
ConfigLoader ()
Static Private Attributes
static const std::string config_path = "./GameData/config.txt"
static const std::string version_path = "./GameData/version.txt"
static std::map< std::string, std::string > configuration = std::map<std::string, std::string>()
map of key to value
static std::string version = std::string()
Detailed Description
Configuration Loader.
Loads and manages Configuration.
Definition at line 15 of file ConfigLoader.hpp.
Member Typedef Documentation
using ConfigLoader::c_iter = std::map<std::string, std::string>::const_iterator private
Definition at line 35 of file ConfigLoader.hpp.
Constructor & Destructor Documentation
ConfigLoader::ConfigLoader () private
Definition at line 8 of file ConfigLoader.cpp.
Member Function Documentation
std::vector< std::pair< std::string, std::string > > ConfigLoader::getAllOptions () static
Definition at line 86 of file ConfigLoader.cpp.
References configuration.
int ConfigLoader::getIntOption (std::string key, int defaultTo = -1) static
Definition at line 46 of file ConfigLoader.cpp.
References getStringOption().
Referenced by World::configure(), WorldChunk::configure(), Game::configure(), and Server::configure().
std::string ConfigLoader::getStringOption (std::string key, std::string defaultTo = "") static
Definition at line 58 of file ConfigLoader.cpp.
References configuration, mutateOption(), and save().
Referenced by Game::configure(), Server::configure(), and getIntOption().
std::string ConfigLoader::getVersion () static
Definition at line 41 of file ConfigLoader.cpp.
References version.
Referenced by Game::configure(), and Server::configure().
void ConfigLoader::load () static
Definition at line 13 of file ConfigLoader.cpp.
References config_path, configuration, version, and version_path.
Referenced by Game::configure(), and Server::configure().
void ConfigLoader::mutateOption (std::string key, int value) static
Definition at line 72 of file ConfigLoader.cpp.
Referenced by getStringOption().
void ConfigLoader::mutateOption (std::string key, std::string value) static
Definition at line 81 of file ConfigLoader.cpp.
References configuration.
void ConfigLoader::save () static
Definition at line 31 of file ConfigLoader.cpp.
References config_path, and configuration.
Referenced by getStringOption().
Member Data Documentation
const std::string ConfigLoader::config_path = "./GameData/config.txt" static private
Definition at line 33 of file ConfigLoader.hpp.
Referenced by load(), and save().
std::map< std::string, std::string > ConfigLoader::configuration = std::map<std::string, std::string>() static private
map of key to value
Definition at line 40 of file ConfigLoader.hpp.
Referenced by getAllOptions(), getStringOption(), load(), mutateOption(), and save().
std::string ConfigLoader::version = std::string() static private
Definition at line 42 of file ConfigLoader.hpp.
Referenced by getVersion(), and load().
const std::string ConfigLoader::version_path = "./GameData/version.txt" static private
Definition at line 34 of file ConfigLoader.hpp.
Referenced by load().
The documentation for this class was generated from the following files:
ConfigLoader.hpp
ConfigLoader.cpp