Arbitrage Simulator: CityPass Class Reference
CityPass Class Reference
#include "CityPass.hpp"
Public Member Functions
void init ()
void execute (World *world, boost::shared_ptr< Logger > logger)
void doTile (int i, int j, Tile *tile)
AbstractPass * clone ()
std::string getName ()
Private Types
enum PassState { Gather = 0, Calc = 1, CityPlace = 2 }
Private Member Functions
void doGather (int i, int j, Tile *tile)
void doPlace (int i, int j, Tile *tile)
void calcDifferentials ()
void calcAvgLivability ()
void convertTileToCity (int i, int j, Tile *tile)
Private Attributes
PassState state
std::vector< std::vector< int > > worldElevations
std::vector< std::vector< float > > worldDiff
std::vector< std::vector< bool > > citySpawnableMask
std::vector< std::vector< int > > livabilityMask
std::vector< std::vector< float > > avgLivabilityMask
NoiseFunc cityConversionNoise
Static Private Attributes
static const std::string name = "Cities"
static constexpr float cityConversionSpread = 50.0
static constexpr float cityConversionRatio = 0.125
static constexpr int minLivibility = 8
static constexpr int maxElevationDiff = 2
static constexpr int citySpawnRadiusMask = 5
Additional Inherited Members
Protected Member Functions inherited from AbstractPass
virtual void executeChunk (int top, int left, WorldChunk *chunk)
Detailed Description
Definition at line 17 of file CityPass.hpp.
Member Enumeration Documentation
enum CityPass::PassState private
Enumerator
Gather
Calc
CityPlace
Definition at line 38 of file CityPass.hpp.
Member Function Documentation
void CityPass::calcAvgLivability () private
Definition at line 90 of file CityPass.cpp.
References avgLivabilityMask, livabilityMask, and worldElevations.
Referenced by execute().
void CityPass::calcDifferentials () private
Definition at line 79 of file CityPass.cpp.
References worldDiff, and worldElevations.
Referenced by execute().
AbstractPass * CityPass::clone () virtual
Implements AbstractPass.
Definition at line 54 of file CityPass.cpp.
void CityPass::convertTileToCity (int i, int j, Tile * tile) private
Definition at line 109 of file CityPass.cpp.
References citySpawnableMask, citySpawnRadiusMask, and Tile::convertToCity().
Referenced by doPlace().
void CityPass::doGather (int i, int j, Tile * tile) private
Definition at line 59 of file CityPass.cpp.
References Tile::canConvertToCity(), citySpawnableMask, Tile::getElevation(), Tile::getLivability(), livabilityMask, and worldElevations.
Referenced by doTile().
void CityPass::doPlace (int i, int j, Tile * tile) private
Definition at line 66 of file CityPass.cpp.
References avgLivabilityMask, cityConversionNoise, cityConversionRatio, citySpawnableMask, convertTileToCity(), NoiseFunc::get(), maxElevationDiff, minLivibility, and worldDiff.
Referenced by doTile().
void CityPass::doTile (int i, int j, Tile * tile) virtual
Implements AbstractPass.
Definition at line 37 of file CityPass.cpp.
References CityPlace, doGather(), doPlace(), Gather, and state.
void CityPass::execute (World * world, boost::shared_ptr< Logger > logger) virtual
Reimplemented from AbstractPass.
Definition at line 19 of file CityPass.cpp.
References Calc, calcAvgLivability(), calcDifferentials(), CityPlace, AbstractPass::execute(), Gather, and state.
std::string CityPass::getName () virtual
Implements AbstractPass.
Definition at line 49 of file CityPass.cpp.
References name.
void CityPass::init () virtual
Reimplemented from AbstractPass.
Definition at line 5 of file CityPass.cpp.
References avgLivabilityMask, cityConversionNoise, cityConversionSpread, citySpawnableMask, WorldChunk::getChunkHeight(), WorldChunk::getChunkWidth(), World::getWorldHeight(), World::getWorldWidth(), livabilityMask, worldDiff, and worldElevations.
Referenced by Generator::DefaultGenerator().
Member Data Documentation
std::vector< std::vector<float> > CityPass::avgLivabilityMask private
Definition at line 58 of file CityPass.hpp.
Referenced by calcAvgLivability(), doPlace(), and init().
NoiseFunc CityPass::cityConversionNoise private
Definition at line 60 of file CityPass.hpp.
Referenced by doPlace(), and init().
constexpr float CityPass::cityConversionRatio = 0.125 static private
Definition at line 31 of file CityPass.hpp.
Referenced by doPlace().
constexpr float CityPass::cityConversionSpread = 50.0 static private
Definition at line 30 of file CityPass.hpp.
Referenced by init().
std::vector< std::vector<bool> > CityPass::citySpawnableMask private
Definition at line 56 of file CityPass.hpp.
Referenced by convertTileToCity(), doGather(), doPlace(), and init().
constexpr int CityPass::citySpawnRadiusMask = 5 static private
Definition at line 36 of file CityPass.hpp.
Referenced by convertTileToCity().
std::vector< std::vector<int> > CityPass::livabilityMask private
Definition at line 57 of file CityPass.hpp.
Referenced by calcAvgLivability(), doGather(), and init().
constexpr int CityPass::maxElevationDiff = 2 static private
Definition at line 33 of file CityPass.hpp.
Referenced by doPlace().
constexpr int CityPass::minLivibility = 8 static private
Definition at line 32 of file CityPass.hpp.
Referenced by doPlace().
const std::string CityPass::name = "Cities" static private
Definition at line 29 of file CityPass.hpp.
Referenced by getName().
PassState CityPass::state private
Definition at line 44 of file CityPass.hpp.
Referenced by doTile(), and execute().
std::vector< std::vector<float> > CityPass::worldDiff private
Definition at line 55 of file CityPass.hpp.
Referenced by calcDifferentials(), doPlace(), and init().
std::vector< std::vector<int> > CityPass::worldElevations private
Definition at line 54 of file CityPass.hpp.
Referenced by calcAvgLivability(), calcDifferentials(), doGather(), and init().
The documentation for this class was generated from the following files:
CityPass.hpp
CityPass.cpp