Trade App: Tile Class Reference
Tile Class Reference
Tile.
#include "Tile.hpp"
Classes
struct TileType
Public Types
enum TileLookup {
PLAINS = 0, MOUNTAINS = 1, WATER = 2, SWAMPS = 3,
HILLS = 5, DESERTS = 6, FORESTS = 7
}
Tile Lookup.
enum TilesReserved { CITIES = 4 }
Reserved Tiles.
Public Member Functions
Tile ()
Tile (int type, int elevation)
Tile (std::stringstream *ss)
void fromStringStream (std::stringstream *ss)
From String Stream.
void toStringStream (std::stringstream *ss)
To String Stream.
bool convertToCity ()
Convert this tile to a city tile if this tile may contain a city.
void drawAt (Screen &screen, int top, int left, bool cull)
Draw this tile.
int getElevation () const
int getType () const
Static Public Member Functions
static Tile randomSpawn (float tileInput=-1.0, float elevationInput=-1.0)
Random Spawn.
static void setPallete ()
Set Pallete.
Static Private Member Functions
static void init ()
Private Attributes
int myType
Index into Tiles.
int myElevation
bool hasBeenVisible
Static Private Attributes
static const int veryLargeMultiplyer = 1000000
static const int elevationMax = 128
static const int TypeCount = 8
static const int allowedSpawnCount = 7
static const int allowedCityCount = 5
static const int AllowedSpawns [allowedSpawnCount]
static const int TilesWhichMayHaveCities [allowedCityCount]
static const TileType Tiles [TypeCount]
Static array of TileType to work as a lookup map, tiles contain the index of their own type to get all metadata about that type from this map.
static ColorPallete tilePallete = ColorPallete()
static bool colorPalleteInitialized = false
Detailed Description
Tile.
A flyweight style class for managing each world unit. To the end user, these appear as simple characters on a screen representing a mountain, or a forest.
Definition at line 21 of file Tile.hpp.
Member Enumeration Documentation
enum Tile::TileLookup
Tile Lookup.
Generalized tiles that may be spawned randomly
Enumerator
PLAINS
MOUNTAINS
WATER
SWAMPS
HILLS
DESERTS
FORESTS
Definition at line 44 of file Tile.hpp.
     {
         PLAINS = 0,
         MOUNTAINS = 1,
         WATER = 2,
         SWAMPS = 3,
         HILLS = 5,
         DESERTS = 6,
         FORESTS = 7
     };
enum Tile::TilesReserved
Reserved Tiles.
Specialized tiles that must be set.
Enumerator
CITIES
Definition at line 59 of file Tile.hpp.
     {
         CITIES = 4
     };
Constructor & Destructor Documentation
Tile::Tile ()
Definition at line 28 of file Tile.cpp.
References hasBeenVisible, init(), and myType.
Referenced by randomSpawn().
 {
     this->myType = 0;
     this->hasBeenVisible = false;
     Tile::init();
 }
Tile::Tile (int type, int elevation)
Definition at line 35 of file Tile.cpp.
References hasBeenVisible, init(), myElevation, and myType.
 {
     this->myType = type;
     this->myElevation = elevation;
     this->hasBeenVisible = false;
     Tile::init();
 }
Tile::Tile (std::stringstream * ss)
Definition at line 81 of file Tile.cpp.
References fromStringStream().
 {
     this->fromStringStream(ss);
 }
Member Function Documentation
bool Tile::convertToCity ()
Convert this tile to a city tile if this tile may contain a city.
Returns
bool If this tile was converted to a city.
Definition at line 101 of file Tile.cpp.
References allowedCityCount, myType, and TilesWhichMayHaveCities.
 {
     bool canConvert = false;
     for(int i = 0; i < Tile::allowedCityCount; ++i) {
         if(this->myType == Tile::TilesWhichMayHaveCities[i]) {
             canConvert = true;
             break;
         }
     }
     if(canConvert) {
         this->myType = TilesReserved::CITIES;
         return true;
     }
     return false;
 }
void Tile::drawAt (Screen & screen, int top, int left, bool cull)
Draw this tile.
Parameters
Screen &screen buffer to draw the tile on to
int top Y coordinate to draw the tile on
int left X coordinate to draw the tile on
bool cull if the player has never seen this tile, do not draw it, If the player has seen this tile, draw it in greyscale.
Definition at line 118 of file Tile.cpp.
References hasBeenVisible, myType, and Screen::put().
 {
     if(!cull) {
         screen.put(
             Tile::Tiles[myType].colorPair,
             /* layer */ 1,
             Tile::Tiles[myType].tile,
             top,
             left
         );
         this->hasBeenVisible = true;
     } else if(this->hasBeenVisible) {
         screen.put(
             /* White on Black */ 5,
             /* layer */ 1,
             Tile::Tiles[myType].tile,
             top,
             left
         );
     }
 }
void Tile::fromStringStream (std::stringstream * ss) virtual
From String Stream.
Assume this object is the next object in the stringstream and restore it's own state based on the stringstream's contents.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 86 of file Tile.cpp.
References hasBeenVisible, myElevation, and myType.
Referenced by Tile().
 {
     (*ss)>>myType>>myElevation>>hasBeenVisible;
 }
int Tile::getElevation () const
Definition at line 154 of file Tile.cpp.
References myElevation.
 {
     return this->myElevation;
 }
int Tile::getType () const
Definition at line 159 of file Tile.cpp.
References myType.
 {
     return this->myType;
 }
void Tile::init () static private
Definition at line 140 of file Tile.cpp.
References ColorPallete::addColor(), and colorPalleteInitialized.
Referenced by randomSpawn(), and Tile().
 {
     if(!Tile::colorPalleteInitialized) {
         Tile::tilePallete.addColor(COLOR_YELLOW, COLOR_BLACK);
         Tile::tilePallete.addColor(COLOR_RED,    COLOR_BLACK);
         Tile::tilePallete.addColor(COLOR_BLUE,   COLOR_BLACK);
         Tile::tilePallete.addColor(COLOR_GREEN,  COLOR_BLACK);
         Tile::tilePallete.addColor(COLOR_CYAN,   COLOR_BLACK);
         Tile::tilePallete.addColor(COLOR_WHITE, COLOR_BLACK);
         Tile::colorPalleteInitialized = true;
     }
 }
Tile Tile::randomSpawn (float tileInput = -1.0, float elevationInput = -1.0) static
Random Spawn.
Factory function which can take a bias and an elevation, then returns a tile allowed at that elevation, with the random choosing biased.
Parameters
float tileInput bias for the random function
float elevationInput elevation that this tile is to spawn at
Definition at line 43 of file Tile.cpp.
References allowedSpawnCount, AllowedSpawns, elevationMax, Tile::TileType::elevationMax, Tile::TileType::elevationMin, init(), Tile(), and veryLargeMultiplyer.
Referenced by WorldChunk::generateChunk().
 {
     Tile::init();
     int spawn = -1;
     int elevation = -1;
     if(elevationInput == -1) {
         elevation = rand() % Tile::elevationMax;
     } else {
         elevation = abs(elevationInput * (float)Tile::elevationMax);
     }
     std::vector<int> spawnsAllowedAtThisElevation;
     for(int i = 0; i < Tile::allowedSpawnCount; ++i) {
         unsigned int min = Tile::Tiles[Tile::AllowedSpawns[i]].elevationMin;
         unsigned int max = Tile::Tiles[Tile::AllowedSpawns[i]].elevationMax;
         if(elevation >= min && elevation <= max) {
             spawnsAllowedAtThisElevation.push_back(AllowedSpawns[i]);
         }
     }
     if(spawnsAllowedAtThisElevation.size() == 0) {
         std::cout<<"ERROR: Can not spawn tile at elevation "<<elevation<<std::endl;
         exit(1);
     }
     if(tileInput == -1) {
         spawn = spawnsAllowedAtThisElevation[rand() % spawnsAllowedAtThisElevation.size()];
     } else {
         float tileToSpawn = tileInput;
         tileToSpawn *= Tile::veryLargeMultiplyer;
         int indexToSpawn = abs((int)tileToSpawn);
         indexToSpawn %= spawnsAllowedAtThisElevation.size();
         spawn = spawnsAllowedAtThisElevation[indexToSpawn];
     }
     return Tile(spawn, elevation);
 }
void Tile::setPallete () static
Set Pallete.
Set the color pallete for all tiles to be the current one.
Definition at line 96 of file Tile.cpp.
References ColorPallete::setCurrent().
Referenced by WorldChunk::draw().
 {
     Tile::tilePallete.setCurrent();
 }
void Tile::toStringStream (std::stringstream * ss) virtual
To String Stream.
Add this object's state into the stringstream at the current point in the stream.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 91 of file Tile.cpp.
References hasBeenVisible, myElevation, and myType.
 {
     (*ss)<<myType<<" "<<myElevation<<" "<<hasBeenVisible;
 }
Member Data Documentation
const int Tile::allowedCityCount = 5 static private
Definition at line 98 of file Tile.hpp.
Referenced by convertToCity().
const int Tile::allowedSpawnCount = 7 static private
Definition at line 97 of file Tile.hpp.
Referenced by randomSpawn().
const int Tile::AllowedSpawns static private
Initial value:
=
{
    0, 1, 2, 3, 5, 6, 7
}
Definition at line 119 of file Tile.hpp.
Referenced by randomSpawn().
bool Tile::colorPalleteInitialized = false static private
Definition at line 130 of file Tile.hpp.
Referenced by init().
const int Tile::elevationMax = 128 static private
Definition at line 95 of file Tile.hpp.
Referenced by randomSpawn().
bool Tile::hasBeenVisible private
Definition at line 137 of file Tile.hpp.
Referenced by drawAt(), fromStringStream(), Tile(), and toStringStream().
int Tile::myElevation private
Definition at line 136 of file Tile.hpp.
Referenced by fromStringStream(), getElevation(), Tile(), and toStringStream().
int Tile::myType private
Index into Tiles.
Definition at line 135 of file Tile.hpp.
Referenced by convertToCity(), drawAt(), fromStringStream(), getType(), Tile(), and toStringStream().
ColorPallete Tile::tilePallete = ColorPallete() static private
Definition at line 129 of file Tile.hpp.
const Tile::TileType Tile::Tiles static private
Initial value:
=
{
    {'-', 5, 30, 60},
    {'^', 1, 50, 128},
    {'#', 2, 0,  40},
    {'#', 3, 20, 40},
    {'C', 4, 0,  0},
    {'n', 5, 45, 80},
    {'_', 0, 20, 30},
    {'T', 3, 45, 75}
}
Static array of TileType to work as a lookup map, tiles contain the index of their own type to get all metadata about that type from this map.
Definition at line 127 of file Tile.hpp.
const int Tile::TilesWhichMayHaveCities static private
Initial value:
=
{
    0, 1, 5, 6, 7
}
Definition at line 120 of file Tile.hpp.
Referenced by convertToCity().
const int Tile::TypeCount = 8 static private
Definition at line 96 of file Tile.hpp.
const int Tile::veryLargeMultiplyer = 1000000 static private
Definition at line 94 of file Tile.hpp.
Referenced by randomSpawn().
The documentation for this class was generated from the following files:
Tile.hpp
Tile.cpp