Trade App: Game Class Reference
Game Class Reference
Manager for Game State.
#include "Game.hpp"
Public Member Functions
Game ()
int setup ()
int run ()
Private Member Functions
void configure ()
std::string checkVersion ()
int login ()
Private Attributes
std::string version
Camera camera
Screen screen
World world
Player player
int screenHeight
int screenWidth
Connection connection
Static Private Attributes
static const std::string configWorldNameKey = "world_name"
static const std::string defaultWorldName = "world"
Detailed Description
Manager for Game State.
Main interface for players playing the game.
Definition at line 29 of file Game.hpp.
Constructor & Destructor Documentation
Game::Game ()
Definition at line 6 of file Game.cpp.
 {
 }
Member Function Documentation
std::string Game::checkVersion () private
Definition at line 114 of file Game.cpp.
References connection, Connection::read(), version, Server::VERSION_CHECK, Server::VERSION_CHECK_OK, Server::VERSION_INCOMPATIBLE, and Connection::write().
Referenced by run().
 {
     std::string message = boost::lexical_cast<std::string>(Server::VERSION_CHECK) + " " + this->version + "\n";
     std::cerr<<message;
     this->connection.write(message);
     std::string response = this->connection.read();
     std::stringstream ss;
     ss.str(response);
     int responseType;
     ss>>responseType;
     if (responseType == Server::VERSION_CHECK_OK) {
         return "";
     } else if (responseType == Server::VERSION_INCOMPATIBLE) {
         std::string serverVersion;
         ss>>serverVersion;
         return serverVersion;
     }
 }
void Game::configure () private
Definition at line 80 of file Game.cpp.
References WorldChunk::configure(), World::configure(), configWorldNameKey, defaultWorldName, ConfigLoader::getIntOption(), ConfigLoader::getStringOption(), ConfigLoader::getVersion(), ConfigLoader::load(), City::load_city_names(), screenHeight, screenWidth, WorldChunk::setMaxYX(), version, and world.
Referenced by setup().
 {
     ConfigLoader::load();
     WorldChunk::configure();
     World::configure();
     City::load_city_names();
     this->world = World(
         ConfigLoader::getStringOption(
             Game::configWorldNameKey,
             Game::defaultWorldName
         )
     );
     this->version = ConfigLoader::getVersion();
     std::cout<<"chunk_height: "<<ConfigLoader::getIntOption("chunk_height")<<'\n';
     std::cout<<"chunk_width: "<<ConfigLoader::getIntOption("chunk_width")<<'\n';
     std::cout<<"max_cities_per_chunk: "<<ConfigLoader::getIntOption("max_cities_per_chunk")<<'\n';
     std::cout<<std::endl;
     unsigned int chunkHeight = ConfigLoader::getIntOption("chunk_height");
     unsigned int chunkWidth  = ConfigLoader::getIntOption("chunk_width");
     int maxY, maxX;
     getmaxyx(stdscr, maxY, maxX);
     this->screenHeight = maxY;
     this->screenWidth = maxX;
     WorldChunk::setMaxYX(maxY, maxX);
 }
int Game::login () private
Definition at line 134 of file Game.cpp.
References connection, Server::LOGIN, and Connection::write().
 {
     std::string message = boost::lexical_cast<std::string>(Server::LOGIN) + " Username Password\n";
     std::cerr<<message;
     this->connection.write(message);
 }
int Game::run ()
Definition at line 25 of file Game.cpp.
References camera, checkVersion(), Screen::clear(), Connection::connect(), connection, Player::getYX(), Player::move(), Camera::moveTo(), player, Camera::render(), Screen::render(), screen, version, and world.
Referenced by main().
 {
     try {
         this->connection.connect("localhost", "9797");
         std::string sVersion;
         if ("" == (sVersion = this->checkVersion())) {
             std::cerr<<"Version OK, good to continue\n";
         } else {
             std::cerr<<"Your version does not match the servers.\nYou are running " +
                 this->version +
                 ".\n The server is running " +
                 sVersion
             ;
             return -1;
         }
     } catch (std::exception& e) {
         std::cerr<<e.what()<<std::endl;
         return -1;
     }
     return 0;
     while(true) {
         int pos_x, pos_y;
         player.getYX(pos_y, pos_x);
         //move camera to player
         this->camera.moveTo(pos_y, pos_x);
         this->camera.render(this->screen, this->world, this->player);
         this->screen.render();
         this->screen.clear();
         unsigned int input = getch();
         switch(input) {
             case KEY_UP:
                 this->player.move(-1,0);
                 break;
             case KEY_DOWN:
                 this->player.move(1,0);
                 break;
             case KEY_LEFT:
                 this->player.move(0,-1);
                 break;
             case KEY_RIGHT:
                 this->player.move(0,1);
                 break;
             case 27: //ESC
                 return 0;
                 break;
         };
     }
     return 0;
 }
int Game::setup ()
Definition at line 11 of file Game.cpp.
References camera, configure(), World::generateWorld(), player, screen, and world.
Referenced by main().
 {
     this->configure();
     this->camera = Camera(0, 0);
     this->screen = Screen();
     this->player = Player("Bob", 0, 0);
     this->world.generateWorld();
     return 0;
 }
Member Data Documentation
Camera Game::camera private
Definition at line 42 of file Game.hpp.
Referenced by run(), and setup().
const std::string Game::configWorldNameKey = "world_name" static private
Definition at line 36 of file Game.hpp.
Referenced by configure().
Connection Game::connection private
Definition at line 50 of file Game.hpp.
Referenced by checkVersion(), login(), and run().
const std::string Game::defaultWorldName = "world" static private
Definition at line 37 of file Game.hpp.
Referenced by configure().
Player Game::player private
Definition at line 45 of file Game.hpp.
Referenced by run(), and setup().
Screen Game::screen private
Definition at line 43 of file Game.hpp.
Referenced by run(), and setup().
int Game::screenHeight private
Definition at line 47 of file Game.hpp.
Referenced by configure().
int Game::screenWidth private
Definition at line 48 of file Game.hpp.
Referenced by configure().
std::string Game::version private
Definition at line 40 of file Game.hpp.
Referenced by checkVersion(), configure(), and run().
World Game::world private
Definition at line 44 of file Game.hpp.
Referenced by configure(), run(), and setup().
The documentation for this class was generated from the following files:
Game.hpp
Game.cpp