Arbitrage Simulator: ItemMap Class Reference
ItemMap Class Reference
#include "ItemMap.hpp"
Static Public Member Functions
static void init (Logger::LoggerPtr logger)
static Item get (int id)
static std::vector< int > validIds ()
Static Private Attributes
static const std::string filename = "GameData/items.txt"
static std::map< int, Item > collection = std::map<int, Item>()
Detailed Description
Definition at line 12 of file ItemMap.hpp.
Member Function Documentation
Item ItemMap::get (int id) static
Definition at line 37 of file ItemMap.cpp.
References collection.
Referenced by CityPass::convertTileToCity(), and GameState::CityInventory::getCityInventory().
void ItemMap::init (Logger::LoggerPtr logger) static
Definition at line 6 of file ItemMap.cpp.
References collection, filename, Item::getBaseWorth(), Item::getDescription(), Item::getId(), Item::getName(), and Item::getWeight().
Referenced by Server::initialize(), and Game::setup().
std::vector< int > ItemMap::validIds () static
Definition at line 42 of file ItemMap.cpp.
References collection.
Referenced by CityPass::convertTileToCity().
Member Data Documentation
std::map< int, Item > ItemMap::collection = std::map<int, Item>() static private
Definition at line 21 of file ItemMap.hpp.
Referenced by get(), init(), and validIds().
const std::string ItemMap::filename = "GameData/items.txt" static private
Definition at line 19 of file ItemMap.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
ItemMap.hpp
ItemMap.cpp