Arbitrage Simulator: BufferLogger Class Reference
BufferLogger Class Reference
BufferLogger.
#include "BufferLogger.hpp"
Public Types
typedef std::pair< Logger::LogLevel, std::string > LogEntry
Public Types inherited from Logger
enum LogLevel {
NONE = 0, DEBUG = 1, INFO = 2, WARN = 3,
ERROR = 4
}
Public Member Functions
BufferLogger ()
virtual ~BufferLogger ()
void setBufferCapacity (int newCapacity)
virtual void debug (const char *fmt,...)
virtual void info (const char *fmt,...)
virtual void warn (const char *fmt,...)
virtual void error (const char *fmt,...)
virtual void log (Logger::LogLevel level, const char *fmt,...)
virtual std::list< LogEntry > & getBuffer ()
int getBufferSize ()
Public Member Functions inherited from Logger
virtual ~Logger ()
Protected Member Functions
virtual void addToBuffer (Logger::LogLevel level, const char *fmt, va_list args)
Protected Member Functions inherited from Logger
virtual std::string format_string (LogLevel level, const char *fmt, va_list args)
std::string get_time ()
Protected Attributes
int bufferCapacity
int bufferSize
std::list< LogEntry > buffer
Static Protected Attributes
static const int defaultCapacity = 50
Static Protected Attributes inherited from Logger
static const std::string levelStrings [4]
static int logLevel = 0
Additional Inherited Members
Static Public Member Functions inherited from Logger
static void configure ()
Detailed Description
BufferLogger.
Log direcly to a vector of strings. Utility class for things like a console window.
Definition at line 19 of file BufferLogger.hpp.
Member Typedef Documentation
typedef std::pair<Logger::LogLevel, std::string> BufferLogger::LogEntry
Definition at line 22 of file BufferLogger.hpp.
Constructor & Destructor Documentation
BufferLogger::BufferLogger ()
Definition at line 5 of file BufferLogger.cpp.
References buffer, bufferCapacity, and defaultCapacity.
BufferLogger::~BufferLogger () virtual
Definition at line 11 of file BufferLogger.cpp.
Member Function Documentation
void BufferLogger::addToBuffer (Logger::LogLevel level, const char * fmt, va_list args) protected virtual
Definition at line 72 of file BufferLogger.cpp.
References buffer, bufferCapacity, bufferSize, Logger::format_string(), and Logger::logLevel.
Referenced by debug(), error(), info(), log(), and warn().
void BufferLogger::debug (const char * fmt, ...) virtual
Implements Logger.
Definition at line 21 of file BufferLogger.cpp.
References addToBuffer(), and Logger::DEBUG.
void BufferLogger::error (const char * fmt, ...) virtual
Implements Logger.
Definition at line 45 of file BufferLogger.cpp.
References addToBuffer(), and Logger::ERROR.
std::list< BufferLogger::LogEntry > & BufferLogger::getBuffer () virtual
Definition at line 62 of file BufferLogger.cpp.
References buffer.
Referenced by ConsoleWindow::render().
int BufferLogger::getBufferSize ()
Definition at line 67 of file BufferLogger.cpp.
References bufferSize.
Referenced by ConsoleWindow::render().
void BufferLogger::info (const char * fmt, ...) virtual
Implements Logger.
Definition at line 29 of file BufferLogger.cpp.
References addToBuffer(), and Logger::INFO.
void BufferLogger::log (Logger::LogLevel level, const char * fmt, ...) virtual
Implements Logger.
Definition at line 54 of file BufferLogger.cpp.
References addToBuffer().
void BufferLogger::setBufferCapacity (int newCapacity)
Definition at line 16 of file BufferLogger.cpp.
References bufferCapacity.
Referenced by ConsoleWindow::ConsoleWindow().
void BufferLogger::warn (const char * fmt, ...) virtual
Implements Logger.
Definition at line 37 of file BufferLogger.cpp.
References addToBuffer(), and Logger::WARN.
Member Data Documentation
std::list<LogEntry> BufferLogger::buffer protected
Definition at line 42 of file BufferLogger.hpp.
Referenced by addToBuffer(), BufferLogger(), and getBuffer().
int BufferLogger::bufferCapacity protected
Definition at line 40 of file BufferLogger.hpp.
Referenced by addToBuffer(), BufferLogger(), and setBufferCapacity().
int BufferLogger::bufferSize protected
Definition at line 41 of file BufferLogger.hpp.
Referenced by addToBuffer(), and getBufferSize().
const int BufferLogger::defaultCapacity = 50 static protected
Definition at line 37 of file BufferLogger.hpp.
Referenced by BufferLogger().
The documentation for this class was generated from the following files:
BufferLogger.hpp
BufferLogger.cpp