Arbitrage Simulator: TypePass Class Reference
TypePass Class Reference
#include "TypePass.hpp"
Public Member Functions
void init ()
void doTile (int i, int j, Tile *tile)
AbstractPass * clone ()
std::string getName ()
Public Member Functions inherited from AbstractPass
virtual void execute (World *world, boost::shared_ptr< Logger > logger)
Private Member Functions
int typeMap (Tile *tile, float tileInput)
Private Attributes
NoiseFunc typeNoise
Static Private Attributes
static const int veryLargeMultiplyer = 1000000
static const std::string name = "Type"
static constexpr float typeNoiseSpread = 20.0
Additional Inherited Members
Protected Member Functions inherited from AbstractPass
virtual void executeChunk (int top, int left, WorldChunk *chunk)
Detailed Description
Definition at line 12 of file TypePass.hpp.
Member Function Documentation
AbstractPass * TypePass::clone () virtual
Implements AbstractPass.
Definition at line 20 of file TypePass.cpp.
void TypePass::doTile (int i, int j, Tile * tile) virtual
Implements AbstractPass.
Definition at line 10 of file TypePass.cpp.
References NoiseFunc::get(), Tile::setType(), typeMap(), and typeNoise.
std::string TypePass::getName () virtual
Implements AbstractPass.
Definition at line 25 of file TypePass.cpp.
References name.
void TypePass::init () virtual
Reimplemented from AbstractPass.
Definition at line 5 of file TypePass.cpp.
References typeNoise, and typeNoiseSpread.
Referenced by Generator::DefaultGenerator().
int TypePass::typeMap (Tile * tile, float tileInput) private
Definition at line 30 of file TypePass.cpp.
References Tile::allowedSpawnCount, Tile::AllowedSpawns, Tile::TileType::elevationMax, Tile::TileType::elevationMin, Tile::getElevation(), Tile::Tiles, and veryLargeMultiplyer.
Referenced by doTile().
Member Data Documentation
const std::string TypePass::name = "Type" static private
Definition at line 23 of file TypePass.hpp.
Referenced by getName().
NoiseFunc TypePass::typeNoise private
Definition at line 29 of file TypePass.hpp.
Referenced by doTile(), and init().
constexpr float TypePass::typeNoiseSpread = 20.0 static private
Definition at line 25 of file TypePass.hpp.
Referenced by init().
const int TypePass::veryLargeMultiplyer = 1000000 static private
Definition at line 22 of file TypePass.hpp.
Referenced by typeMap().
The documentation for this class was generated from the following files:
TypePass.hpp
TypePass.cpp