Trade App: Server Class Reference
Server Class Reference
Server Manager.
#include "Server.hpp"
Public Types
enum REQUST_TYPE {
ERROR = 0, VERSION_CHECK = 1, VERSION_CHECK_OK = 2, VERSION_INCOMPATIBLE = 3,
LOGIN = 10, REQUEST_CHARACTER = 100, REQUEST_WORLD = 110, REQUEST_CHUNK = 120,
REQUEST_CITY = 130
}
Request Type.
Public Member Functions
Server ()
int setup ()
int run ()
Private Member Functions
void initialize ()
void configure ()
void manageSession (int connectionIndex, int threadIndex)
void cleanup ()
Static Private Member Functions
static std::string VersionCheckHandler (Server &myself, std::string msg)
Request Handler: Version Check.
static std::string LoginHandler (Server &myself, std::string msg)
Request Handler: Login Handler Check for existing user with same username and password, if match then this session may use that users character.
Private Attributes
int portNumber
std::string version
World world
std::vector< std::thread > threads
std::vector< int > closed
std::mutex closedMutex
std::vector< Connection > connections
std::thread cleaner
Static Private Attributes
static const std::string configWorldNameKey = "world_name"
static const std::string defaultWorldName = "world"
static const std::string configPortNumberKey = "server_port"
static const int defaultPortNumber = 9797
static std::map< int, std::string(*)(Server &myself, std::string msg)> requestMap
Request Handlers.
Detailed Description
Server Manager.
Dispatcher and manager for all server sessions. Owns and maintains world state.
Definition at line 26 of file Server.hpp.
Member Enumeration Documentation
enum Server::REQUST_TYPE
Request Type.
An enumeration of all possible requests a client can make, or responses a server can return.
Enumerator
ERROR
VERSION_CHECK
VERSION_CHECK_OK
VERSION_INCOMPATIBLE
LOGIN
REQUEST_CHARACTER
REQUEST_WORLD
REQUEST_CHUNK
REQUEST_CITY
Definition at line 38 of file Server.hpp.
                      {
         ERROR = 0,
         VERSION_CHECK = 1,
         VERSION_CHECK_OK = 2,
         VERSION_INCOMPATIBLE = 3,
         LOGIN = 10,
         REQUEST_CHARACTER = 100,
         REQUEST_WORLD = 110,
         REQUEST_CHUNK = 120,
         REQUEST_CITY = 130,
     };
Constructor & Destructor Documentation
Server::Server ()
Definition at line 15 of file Server.cpp.
 {
 }
Member Function Documentation
void Server::cleanup () private
Definition at line 103 of file Server.cpp.
References closed, closedMutex, and threads.
Referenced by initialize().
 {
     while (true) {
         std::unique_lock<std::mutex> lock(closedMutex, std::try_to_lock);
         if(lock.owns_lock()) {
             for (int i = 0; i < this->closed.size(); ++i) {
                 this->threads[this->closed[i]] = std::thread(std::move(this->threads[this->threads.size() - 1]));
                 this->threads.pop_back();
             }
             this->closed.clear();
         } else {
             std::cerr<<"Lock on cleanup threads failed.";
         }
         std::this_thread::sleep_for(std::chrono::seconds(5));
     }
 }
void Server::configure () private
Definition at line 54 of file Server.cpp.
References configPortNumberKey, configWorldNameKey, defaultPortNumber, defaultWorldName, ConfigLoader::getIntOption(), ConfigLoader::getStringOption(), ConfigLoader::getVersion(), ConfigLoader::load(), portNumber, version, and world.
Referenced by setup().
 {
     ConfigLoader::load();
     this->portNumber = ConfigLoader::getIntOption(
         Server::configPortNumberKey,
         Server::defaultPortNumber
     );
     this->version = ConfigLoader::getVersion();
     this->world = World(
         ConfigLoader::getStringOption(
             Server::configWorldNameKey,
             Server::defaultWorldName
         )
     );
 }
void Server::initialize () private
Definition at line 49 of file Server.cpp.
References cleaner, and cleanup().
Referenced by setup().
 {
     this->cleaner = std::thread(&Server::cleanup, this);
 }
std::string Server::LoginHandler (Server & myself, std::string msg) static private
Request Handler: Login Handler Check for existing user with same username and password, if match then this session may use that users character.
Otherwise, deny access.
Parameters
Server &myself
std::string msg the message the client sent
Returns
std::string the response
Definition at line 141 of file Server.cpp.
 {
     int type;
     std::string username, password;
     std::stringstream ss;
     ss.str(msg);
     ss>>type>>username>>password;
     return "Welcome, " + username;
 }
void Server::manageSession (int connectionIndex, int threadIndex) private
Definition at line 73 of file Server.cpp.
References closed, connections, ERROR, and requestMap.
Referenced by run().
 {
     while (true) {
         try {
             std::string message = this->connections[connectionIndex].read();
             std::cout<<message<<std::endl;
             std::stringstream ss;
             int request_type;
             ss.str(message);
             ss>>request_type;
             std::string response = boost::lexical_cast<std::string>(ERROR) + " invalid message";
             if (this->requestMap.find(request_type) != this->requestMap.end()) {
                 response = this->requestMap[request_type](*this, message);
             }
             std::cout<<response;
             this->connections[connectionIndex].write(response);
         } catch(std::exception& e) {
             std::cerr<<e.what()<<std::endl;
             this->connections[connectionIndex].close();
             this->connections[connectionIndex] = this->connections[this->connections.size() - 1];
             this->connections.pop_back();
             this->closed.push_back(threadIndex);
             return;
         }
     }
 }
int Server::run ()
Definition at line 27 of file Server.cpp.
References connections, manageSession(), portNumber, and threads.
Referenced by main().
 {
     using boost::asio::ip::tcp;
     boost::asio::io_service io_service;
     tcp::acceptor acceptor(io_service, tcp::endpoint(tcp::v4(), this->portNumber));
     while (true) {
         Connection::socket_ptr sock(new tcp::socket(io_service));
         int connectionIndex = this->connections.size();
         this->connections.push_back(Connection());
         this->connections[connectionIndex].bind(sock);
         acceptor.accept(*this->connections[connectionIndex].get());
         if (threads.size() < 32) {
             int threadIndex = this->threads.size();
             this->threads.push_back(std::thread(&Server::manageSession, this, connectionIndex, threadIndex));
         } else {
             std::cerr<<threads.size()<<" connections open already, connection denied"<<std::endl;
             this->connections[connectionIndex].close();
         }
     }
     return 0;
 }
int Server::setup ()
Definition at line 20 of file Server.cpp.
References configure(), and initialize().
Referenced by main().
 {
     this->configure();
     this->initialize();
     return 0;
 }
std::string Server::VersionCheckHandler (Server & myself, std::string msg) static private
Request Handler: Version Check.
Handle a request to check the compatibility of this server and a client.
Parameters
Server &myself
std::string msg the message the client sent
Returns
std::string the response
Definition at line 120 of file Server.cpp.
References version, VERSION_CHECK_OK, and VERSION_INCOMPATIBLE.
 {
     int type;
     std::string version;
     std::stringstream ss;
     ss.str(msg);
     ss>>type>>version;
     std::cout<<"Client request version check ";
     if (myself.version == version) {
         std::cout<<"version OK\n";
         return boost::lexical_cast<std::string>(Server::VERSION_CHECK_OK) + "\n";
     } else {
         std::cout<<"version INCOMPATIBLE\n";
         return boost::lexical_cast<std::string>(Server::VERSION_INCOMPATIBLE) +
             " " +
             myself.version +
             "\n"
         ;
     }
 }
Member Data Documentation
std::thread Server::cleaner private
Definition at line 69 of file Server.hpp.
Referenced by initialize().
std::vector<int> Server::closed private
Definition at line 66 of file Server.hpp.
Referenced by cleanup(), and manageSession().
std::mutex Server::closedMutex private
Definition at line 67 of file Server.hpp.
Referenced by cleanup().
const std::string Server::configPortNumberKey = "server_port" static private
Definition at line 52 of file Server.hpp.
Referenced by configure().
const std::string Server::configWorldNameKey = "world_name" static private
Definition at line 50 of file Server.hpp.
Referenced by configure().
std::vector<Connection> Server::connections private
Definition at line 68 of file Server.hpp.
Referenced by manageSession(), and run().
const int Server::defaultPortNumber = 9797 static private
Definition at line 53 of file Server.hpp.
Referenced by configure().
const std::string Server::defaultWorldName = "world" static private
Definition at line 51 of file Server.hpp.
Referenced by configure().
int Server::portNumber private
Definition at line 55 of file Server.hpp.
Referenced by configure(), and run().
std::map< int, std::string(*)(Server &myself, std::string msg)> Server::requestMap static private
Initial value:
=
    {
        {Server::VERSION_CHECK, VersionCheckHandler},
        {Server::LOGIN, LoginHandler}
    }
Request Handlers.
All handlers will take a string message and return a string response
Definition at line 77 of file Server.hpp.
Referenced by manageSession().
std::vector<std::thread> Server::threads private
Definition at line 65 of file Server.hpp.
Referenced by cleanup(), and run().
std::string Server::version private
Definition at line 56 of file Server.hpp.
Referenced by configure(), and VersionCheckHandler().
World Server::world private
Definition at line 63 of file Server.hpp.
Referenced by configure().
The documentation for this class was generated from the following files:
Server.hpp
Server.cpp