Trade App: World Class Reference
World Class Reference
World.
#include "World.hpp"
Public Member Functions
World ()
World (std::stringstream *ss)
World (std::string name)
void fromStringStream (std::stringstream *ss)
void toStringStream (std::stringstream *ss)
void generateWorld ()
void draw (Screen &screen, int playerY, int playerX)
Static Public Member Functions
static void configure ()
static int getWorldHeight ()
static int getWorldWidth ()
Private Member Functions
void init ()
Initialize.
void spawnChunk (int y, int x)
Spawn a chunk at x,y.
WorldChunk prepareChunk (int y, int x)
Prepare Chunk.
Private Attributes
int chunkHeight
int chunkWidth
std::vector< std::vector< WorldChunk > > chunks
std::string name
time_t creationTimestamp
NoiseFunc elevationSkewNoise
NoiseFunc elevationNoise
NoiseFunc tileNoise
Static Private Attributes
static constexpr float elevationSkewNoiseSpread = 55.0
static constexpr float elevationNoiseSpread = 20.0
static constexpr float tileNoiseSpread = 6.0
static unsigned int worldHeight = 0
static unsigned int worldWidth = 0
Detailed Description
World.
Owner of all game objects. The world is composed of many world chunks that can be individually replicated.
Definition at line 21 of file World.hpp.
Constructor & Destructor Documentation
World::World ()
Definition at line 6 of file World.cpp.
References init().
 {
     this->init();
 }
World::World (std::stringstream * ss)
Definition at line 11 of file World.cpp.
References fromStringStream(), and init().
 {
     this->init();
     this->fromStringStream(ss);
 }
World::World (std::string name)
Definition at line 17 of file World.cpp.
References init(), and name.
 {
     this->init();
     this->name = name;
 }
Member Function Documentation
void World::configure () static
Definition at line 23 of file World.cpp.
References ConfigLoader::getIntOption(), worldHeight, and worldWidth.
Referenced by Game::configure().
 {
     World::worldHeight = ConfigLoader::getIntOption("world_height", 20);
     World::worldWidth = ConfigLoader::getIntOption("world_width", 20);
 }
void World::draw (Screen & screen, int playerY, int playerX)
Definition at line 65 of file World.cpp.
References chunks.
Referenced by Camera::render().
 {
     for(int i = 0; i < this->chunks.size(); ++i) {
         for(int j = 0; j < this->chunks[i].size(); ++j) {
             this->chunks[i][j].draw(screen, playerY, playerX);
         }
     }
 }
void World::fromStringStream (std::stringstream * ss)
Definition at line 29 of file World.cpp.
References chunks, creationTimestamp, and name.
Referenced by World().
 {
     int sizeY, sizeX;
     (*ss)>>this->name>>this->creationTimestamp;
     (*ss)>>sizeY>>sizeX;
     for(int i = 0; i < sizeY; ++i) {
             this->chunks.push_back(std::vector<WorldChunk>());
         for(int j = 0; j < sizeX; ++j) {
             this->chunks[i].push_back(WorldChunk(ss));
         }
     }
 }
void World::generateWorld ()
Definition at line 54 of file World.cpp.
References chunkHeight, chunkWidth, creationTimestamp, WorldChunk::getChunkHeight(), WorldChunk::getChunkWidth(), spawnChunk(), worldHeight, and worldWidth.
Referenced by Game::setup().
 {
     this->creationTimestamp = time(NULL);
     this->chunkHeight = WorldChunk::getChunkHeight();
     this->chunkWidth = WorldChunk::getChunkWidth();
     //spawning the bottom left chunk spawns all interim chunks.
     this->spawnChunk(World::worldHeight, World::worldWidth);
 }
int World::getWorldHeight () static
Definition at line 110 of file World.cpp.
References worldHeight.
 {
     return World::worldHeight;
 }
int World::getWorldWidth () static
Definition at line 115 of file World.cpp.
References worldWidth.
 {
     return World::worldWidth;
 }
void World::init () private
Initialize.
Setup required variables and state before object can be used.
Todo:
: when adding saving and loading world, the noise functions will have to be added to the get from and add to stringstream functions.
Definition at line 74 of file World.cpp.
References elevationNoise, elevationNoiseSpread, elevationSkewNoise, elevationSkewNoiseSpread, tileNoise, and tileNoiseSpread.
Referenced by World().
 {
     this->elevationSkewNoise = NoiseFunc(World::elevationSkewNoiseSpread);
     this->elevationNoise = NoiseFunc(World::elevationNoiseSpread);
     this->tileNoise = NoiseFunc(World::tileNoiseSpread);
 }
WorldChunk World::prepareChunk (int y, int x) private
Prepare Chunk.
Factory method for world chunks.
Parameters
int y y location in the noise functions to use
int x x location in the noise funcitons to use
Returns
WorldChunk
Definition at line 103 of file World.cpp.
References elevationNoise, elevationSkewNoise, WorldChunk::generateChunk(), and tileNoise.
Referenced by spawnChunk().
 {
     WorldChunk temp(y, x);
     temp.generateChunk(&this->tileNoise, &this->elevationNoise, &this->elevationSkewNoise);
     return temp;
 }
void World::spawnChunk (int y, int x) private
Spawn a chunk at x,y.
This is actually sort of a misnomer, having a chunk at x,y requires chunks at all positions smaller than x,y, so this function expands the chunk grid to x,y spawning chunks to fill the gaps.
Parameters
int y y position in the grid to add a worldChunk
int x x position in the grid to add a worldChunk
Definition at line 81 of file World.cpp.
References chunks, and prepareChunk().
Referenced by generateWorld().
 {
     int size_y = this->chunks.size();
     int size_x = (size_y > 0) ? this->chunks[0].size() : 0;
     int dy = (y+1) - size_y;
     int dx = (x+1) - size_x;
     for(int i = 0; i < dy; ++i) {
         this->chunks.push_back(std::vector<WorldChunk>());
         int fillY = this->chunks.size() - 1;
         for(int j = 0; j < chunks[0].size(); ++j) {
             this->chunks[fillY].push_back(this->prepareChunk(fillY, j));
         }
     }
     for(int i = 0; i < dx; ++i) {
         for(int j = 0; j < this->chunks.size(); ++j) {
             this->chunks[j].push_back(this->prepareChunk(j, i));
         }
     }
 }
void World::toStringStream (std::stringstream * ss)
Definition at line 42 of file World.cpp.
References chunks, creationTimestamp, and name.
 {
     (*ss)<<this->name<<" "<<this->creationTimestamp<<" ";
     (*ss)<<this->chunks.size()<<" "<<this->chunks[0].size()<<"\n";
     for(int i = 0; i < this->chunks.size(); ++i) {
         for(int j = 0; j < this->chunks[i].size(); ++j) {
             this->chunks[i][j].toStringStream(ss);
             (*ss)<<"\n";
         }
     }
 }
Member Data Documentation
int World::chunkHeight private
Definition at line 45 of file World.hpp.
Referenced by generateWorld().
std::vector< std::vector<WorldChunk> > World::chunks private
Definition at line 78 of file World.hpp.
Referenced by draw(), fromStringStream(), spawnChunk(), and toStringStream().
int World::chunkWidth private
Definition at line 46 of file World.hpp.
Referenced by generateWorld().
time_t World::creationTimestamp private
Definition at line 80 of file World.hpp.
Referenced by fromStringStream(), generateWorld(), and toStringStream().
NoiseFunc World::elevationNoise private
Definition at line 83 of file World.hpp.
Referenced by init(), and prepareChunk().
constexpr float World::elevationNoiseSpread = 20.0 static private
Definition at line 40 of file World.hpp.
Referenced by init().
NoiseFunc World::elevationSkewNoise private
Definition at line 82 of file World.hpp.
Referenced by init(), and prepareChunk().
constexpr float World::elevationSkewNoiseSpread = 55.0 static private
Definition at line 39 of file World.hpp.
Referenced by init().
std::string World::name private
Definition at line 79 of file World.hpp.
Referenced by fromStringStream(), toStringStream(), and World().
NoiseFunc World::tileNoise private
Definition at line 84 of file World.hpp.
Referenced by init(), and prepareChunk().
constexpr float World::tileNoiseSpread = 6.0 static private
Definition at line 41 of file World.hpp.
Referenced by init().
unsigned int World::worldHeight = 0 static private
Definition at line 43 of file World.hpp.
Referenced by configure(), generateWorld(), and getWorldHeight().
unsigned int World::worldWidth = 0 static private
Definition at line 44 of file World.hpp.
Referenced by configure(), generateWorld(), and getWorldWidth().
The documentation for this class was generated from the following files:
World.hpp
World.cpp