Arbitrage Simulator: Window Class Reference
Window Class Reference abstract
Window.
#include "Window.hpp"
Classes
struct TextElement
Public Types
typedef boost::shared_ptr< Window > window_ptr
Public Member Functions
virtual ~Window ()
virtual void init ()=0
virtual void putstr (int y, int x, std::string str, int color=0)=0
virtual void put (unsigned int colorPair, unsigned int layer, char c, int y, int x)=0
virtual void put (TextElement c, int y, int x)=0
virtual void clear ()=0
virtual void render ()=0
virtual void resize (int height, int width)=0
virtual void move (int y, int x)=0
virtual int getCh ()=0
virtual int getY ()=0
virtual int getX ()=0
virtual int getHeight ()=0
virtual int getWidth ()=0
Detailed Description
Window.
Interface for all windows to follow.
Definition at line 13 of file Window.hpp.
Member Typedef Documentation
typedef boost::shared_ptr<Window> Window::window_ptr
Definition at line 22 of file Window.hpp.
Constructor & Destructor Documentation
virtual Window::~Window () inline virtual
Definition at line 23 of file Window.hpp.
References Window::TextElement::c, clear(), Window::TextElement::colorPair, getCh(), getHeight(), getWidth(), getX(), getY(), init(), Window::TextElement::layer, move(), put(), putstr(), render(), and resize().
Member Function Documentation
virtual void Window::clear () pure virtual
Implemented in CursesWindow, and GameWindow.
Referenced by ~Window().
virtual int Window::getCh () pure virtual
Implemented in CursesWindow.
Referenced by ~Window().
virtual int Window::getHeight () pure virtual
Implemented in CursesWindow.
Referenced by ~Window().
virtual int Window::getWidth () pure virtual
Implemented in CursesWindow.
Referenced by ~Window().
virtual int Window::getX () pure virtual
Implemented in CursesWindow.
Referenced by ~Window().
virtual int Window::getY () pure virtual
Implemented in CursesWindow.
Referenced by ~Window().
virtual void Window::init () pure virtual
Implemented in CursesWindow, and GameWindow.
Referenced by ~Window().
virtual void Window::move (int y, int x) pure virtual
Implemented in CursesWindow.
Referenced by ~Window().
virtual void Window::put (unsigned int colorPair, unsigned int layer, char c, int y, int x) pure virtual
Implemented in CursesWindow, and GameWindow.
Referenced by ~Window().
virtual void Window::put (TextElement c, int y, int x) pure virtual
Implemented in CursesWindow, and GameWindow.
virtual void Window::putstr (int y, int x, std::string str, int color = 0) pure virtual
Implemented in CursesWindow, and GameWindow.
Referenced by ~Window().
virtual void Window::render () pure virtual
Implemented in CursesWindow, GameWindow, and ConsoleWindow.
Referenced by ~Window().
virtual void Window::resize (int height, int width) pure virtual
Implemented in CursesWindow, and GameWindow.
Referenced by ~Window().
The documentation for this class was generated from the following file:
Window.hpp