Trade App: GameWindowLayout Class Reference
GameWindowLayout Class Reference
#include "GameWindowLayout.hpp"
Public Member Functions
GameWindowLayout ()
~GameWindowLayout ()
void addWindow (std::string name, Window::window_ptr window)
void delWindow (std::string name)
void setMainWindow (std::string name)
void setSubWindow (std::string name)
void setSubWindowMinHeight (int height)
void render ()
void updateScreenSize (bool force=false)
Private Attributes
Window::window_ptr mainWindow
Window::window_ptr subWindow
std::map< std::string, Window::window_ptr > windows
int windowHeight
int windowWidth
int subWindowMinHeight
Static Private Attributes
static const float screenRatioForMainWindow = 0.80
Detailed Description
Definition at line 13 of file GameWindowLayout.hpp.
Constructor & Destructor Documentation
GameWindowLayout::GameWindowLayout ()
Definition at line 5 of file GameWindowLayout.cpp.
GameWindowLayout::~GameWindowLayout ()
Definition at line 9 of file GameWindowLayout.cpp.
Member Function Documentation
void GameWindowLayout::addWindow (std::string name, Window::window_ptr window)
Definition at line 13 of file GameWindowLayout.cpp.
References windows.
Referenced by Game::setup().
void GameWindowLayout::delWindow (std::string name)
Definition at line 23 of file GameWindowLayout.cpp.
References windows.
void GameWindowLayout::render ()
Definition at line 61 of file GameWindowLayout.cpp.
References mainWindow, subWindow, and updateScreenSize().
Referenced by Game::run(), and Game::setup().
void GameWindowLayout::setMainWindow (std::string name)
Definition at line 33 of file GameWindowLayout.cpp.
References mainWindow, updateScreenSize(), and windows.
Referenced by Game::setup().
void GameWindowLayout::setSubWindow (std::string name)
Definition at line 44 of file GameWindowLayout.cpp.
References subWindow, updateScreenSize(), and windows.
Referenced by Game::setup().
void GameWindowLayout::setSubWindowMinHeight (int height)
Definition at line 55 of file GameWindowLayout.cpp.
References subWindowMinHeight, and updateScreenSize().
void GameWindowLayout::updateScreenSize (bool force = false)
Definition at line 69 of file GameWindowLayout.cpp.
References mainWindow, screenRatioForMainWindow, subWindow, subWindowMinHeight, windowHeight, and windowWidth.
Referenced by render(), setMainWindow(), setSubWindow(), and setSubWindowMinHeight().
Member Data Documentation
Window::window_ptr GameWindowLayout::mainWindow private
Definition at line 32 of file GameWindowLayout.hpp.
Referenced by render(), setMainWindow(), and updateScreenSize().
const float GameWindowLayout::screenRatioForMainWindow = 0.80 static private
Definition at line 30 of file GameWindowLayout.hpp.
Referenced by updateScreenSize().
Window::window_ptr GameWindowLayout::subWindow private
Definition at line 33 of file GameWindowLayout.hpp.
Referenced by render(), setSubWindow(), and updateScreenSize().
int GameWindowLayout::subWindowMinHeight private
Definition at line 39 of file GameWindowLayout.hpp.
Referenced by setSubWindowMinHeight(), and updateScreenSize().
int GameWindowLayout::windowHeight private
Definition at line 36 of file GameWindowLayout.hpp.
Referenced by updateScreenSize().
std::map<std::string, Window::window_ptr> GameWindowLayout::windows private
Definition at line 34 of file GameWindowLayout.hpp.
Referenced by addWindow(), delWindow(), setMainWindow(), and setSubWindow().
int GameWindowLayout::windowWidth private
Definition at line 37 of file GameWindowLayout.hpp.
Referenced by updateScreenSize().
The documentation for this class was generated from the following files:
GameWindowLayout.hpp
GameWindowLayout.cpp