Trade App: Connection Class Reference
Connection Class Reference
Connection.
#include "Connection.hpp"
Public Types
typedef boost::shared_ptr< tcp::socket > socket_ptr
Public Member Functions
Connection ()
Connection (std::string ip, std::string port)
Connection (socket_ptr sock)
void connect (std::string ip, std::string port)
void bind (socket_ptr sock)
If a connection was already made, bind this Connection class to it.
std::string read ()
Blocking read on this socket.
bool write (std::string msg)
Write msg to this socket.
void close ()
socket_ptr get ()
bool isConnected ()
Private Attributes
bool connected
socket_ptr socket
Detailed Description
Connection.
Wrapper for boost sockets to make reading and writing easier.
Definition at line 17 of file Connection.hpp.
Member Typedef Documentation
typedef boost::shared_ptr<tcp::socket> Connection::socket_ptr
Definition at line 20 of file Connection.hpp.
Constructor & Destructor Documentation
Connection::Connection ()
Definition at line 3 of file Connection.cpp.
References connected.
 {
     this->connected = false;
 }
Connection::Connection (std::string ip, std::string port)
Definition at line 8 of file Connection.cpp.
References connect().
 {
     this->connect(ip, port);
 }
Connection::Connection (socket_ptr sock)
Definition at line 13 of file Connection.cpp.
References connected, and socket.
 {
     this->socket = sock;
     this->connected = true;
 }
Member Function Documentation
void Connection::bind (socket_ptr sock)
If a connection was already made, bind this Connection class to it.
Parameters
socket_ptr sock
Definition at line 33 of file Connection.cpp.
References connected, and socket.
Referenced by Server::run().
 {
     this->socket.swap(sock);
     this->connected = true;
 }
void Connection::close ()
Definition at line 76 of file Connection.cpp.
References connected, and socket.
Referenced by Server::run(), and ServerSession::sessionLoop().
 {
     this->socket->close();
     this->connected = false;
 }
void Connection::connect (std::string ip, std::string port)
Definition at line 19 of file Connection.cpp.
References connected, and socket.
Referenced by Connection(), and Game::run().
 {
     if (this->connected) {
         this->socket.reset();
     }
     boost::asio::io_service io_service;
     tcp::resolver resolver(io_service);
     tcp::resolver::query query(ip.c_str(), port.c_str());
     tcp::resolver::iterator endpoint_iterator = resolver.resolve(query);
     this->socket.reset(new tcp::socket(io_service));
     boost::asio::connect(*this->socket, endpoint_iterator);
     this->connected = true;
 }
Connection::socket_ptr Connection::get ()
Definition at line 82 of file Connection.cpp.
References socket.
Referenced by Server::run().
 {
     return this->socket;
 }
bool Connection::isConnected ()
Definition at line 87 of file Connection.cpp.
References connected.
 {
     return this->connected;
 }
std::string Connection::read ()
Blocking read on this socket.
Returns
std::string
Definition at line 39 of file Connection.cpp.
References connected, and socket.
Referenced by Game::checkVersion(), and ServerSession::sessionLoop().
 {
     if (this->connected) {
         boost::system::error_code error;
         boost::asio::streambuf sb;
         std::size_t len = boost::asio::read_until(
             *this->socket,
             sb,
             "\n",
             error
         );
         std::string buff;
         buff.resize(len);
         sb.sgetn(&buff[0], buff.size());
         if (error) {
             throw boost::system::system_error(error);
         }
         return buff;
     } else {
         return "";
     }
 }
bool Connection::write (std::string msg)
Write msg to this socket.
Parameters
std::string msg
Returns
bool success
Definition at line 64 of file Connection.cpp.
References connected, and socket.
Referenced by Game::checkVersion(), Game::login(), ServerSession::sessionLoop(), and ServerSession::write().
 {
     if (this->connected) {
         boost::system::error_code ignored_error;
         boost::asio::write(
             *this->socket,
             boost::asio::buffer(msg),
             ignored_error
         );
     }
 }
Member Data Documentation
bool Connection::connected private
Definition at line 54 of file Connection.hpp.
Referenced by bind(), close(), connect(), Connection(), isConnected(), read(), and write().
socket_ptr Connection::socket private
Definition at line 55 of file Connection.hpp.
Referenced by bind(), close(), connect(), Connection(), get(), read(), and write().
The documentation for this class was generated from the following files:
Connection.hpp
Connection.cpp