Arbitrage Simulator: Generator Class Reference
Generator Class Reference
#include "Generator.hpp"
Public Member Functions
Generator ()
~Generator ()
Generator (const Generator &other)
Generator * operator= (const Generator &other)
void addPass (AbstractPass *pass)
void execute (World *world, boost::shared_ptr< Logger > logger)
Static Public Member Functions
static Generator DefaultGenerator ()
Private Attributes
std::vector< AbstractPass * > passes
Detailed Description
Definition at line 15 of file Generator.hpp.
Constructor & Destructor Documentation
Generator::Generator ()
Definition at line 3 of file Generator.cpp.
References passes.
Generator::~Generator ()
Definition at line 8 of file Generator.cpp.
References passes.
Generator::Generator (const Generator & other)
Definition at line 15 of file Generator.cpp.
References passes.
Member Function Documentation
void Generator::addPass (AbstractPass * pass)
Definition at line 50 of file Generator.cpp.
References passes.
Referenced by DefaultGenerator().
Generator Generator::DefaultGenerator () static
Definition at line 31 of file Generator.cpp.
References addPass(), ElevationPass::init(), TypePass::init(), and CityPass::init().
Referenced by LocalWorldInteraction::LocalWorldInteraction().
void Generator::execute (World * world, boost::shared_ptr< Logger > logger)
Definition at line 55 of file Generator.cpp.
References passes.
Referenced by LocalWorldInteraction::loadWorld().
Generator * Generator::operator= (const Generator & other)
Definition at line 23 of file Generator.cpp.
References passes.
Member Data Documentation
std::vector<AbstractPass*> Generator::passes private
Definition at line 29 of file Generator.hpp.
Referenced by addPass(), execute(), Generator(), operator=(), and ~Generator().
The documentation for this class was generated from the following files:
Generator.hpp
Generator.cpp