Arbitrage Simulator: ElevationPass Class Reference
ElevationPass Class Reference
#include "ElevationPass.hpp"
Public Member Functions
void init ()
void doTile (int i, int j, Tile *tile, WorldChunk *chunk)
AbstractPass * clone ()
std::string getName ()
Public Member Functions inherited from AbstractPass
virtual void execute (World *world, boost::shared_ptr< Logger > logger)
Private Member Functions
float elevationMap (float input, float skew)
Private Attributes
NoiseFunc elevationSkewNoise
NoiseFunc elevationNoise
Static Private Attributes
static const std::string name = "Elevation"
static constexpr float elevationSkewNoiseSpread = 55.0
static constexpr float elevationNoiseSpread = 20.0
Additional Inherited Members
Protected Member Functions inherited from AbstractPass
virtual void executeChunk (int top, int left, WorldChunk *chunk)
Detailed Description
Definition at line 11 of file ElevationPass.hpp.
Member Function Documentation
AbstractPass * ElevationPass::clone () virtual
Implements AbstractPass.
Definition at line 26 of file ElevationPass.cpp.
void ElevationPass::doTile (int i, int j, Tile * tile, WorldChunk * chunk) virtual
Implements AbstractPass.
Definition at line 11 of file ElevationPass.cpp.
References elevationMap(), elevationNoise, elevationSkewNoise, NoiseFunc::get(), and Tile::setElevation().
float ElevationPass::elevationMap (float input, float skew) private
Definition at line 31 of file ElevationPass.cpp.
References Tile::elevationMax.
Referenced by doTile().
std::string ElevationPass::getName () virtual
Implements AbstractPass.
Definition at line 21 of file ElevationPass.cpp.
References name.
void ElevationPass::init () virtual
Reimplemented from AbstractPass.
Definition at line 5 of file ElevationPass.cpp.
References elevationNoise, elevationNoiseSpread, elevationSkewNoise, and elevationSkewNoiseSpread.
Referenced by Generator::DefaultGenerator().
Member Data Documentation
NoiseFunc ElevationPass::elevationNoise private
Definition at line 29 of file ElevationPass.hpp.
Referenced by doTile(), and init().
constexpr float ElevationPass::elevationNoiseSpread = 20.0 static private
Definition at line 26 of file ElevationPass.hpp.
Referenced by init().
NoiseFunc ElevationPass::elevationSkewNoise private
Definition at line 28 of file ElevationPass.hpp.
Referenced by doTile(), and init().
constexpr float ElevationPass::elevationSkewNoiseSpread = 55.0 static private
Definition at line 25 of file ElevationPass.hpp.
Referenced by init().
const std::string ElevationPass::name = "Elevation" static private
Definition at line 21 of file ElevationPass.hpp.
Referenced by getName().
The documentation for this class was generated from the following files:
ElevationPass.hpp
ElevationPass.cpp