Trade App: WorldInteractionInterface Class Reference
WorldInteractionInterface Class Reference abstract
Class to proxy all interactions with the world through.
#include "WorldInteractionInterface.hpp"
Public Member Functions
virtual void loadWorld ()=0
virtual void draw (Window::window_ptr window)=0
virtual void movePlayerToCoordinate (int y, int x)=0
Detailed Description
Class to proxy all interactions with the world through.
Proxy all world interactions through this class so that networked and local gameplay can use a common interface and only differ in which class they instantiate.
Definition at line 13 of file WorldInteractionInterface.hpp.
Member Function Documentation
virtual void WorldInteractionInterface::draw (Window::window_ptr window) pure virtual
Implemented in NetworkedWorldInteraction, and LocalWorldInteraction.
Referenced by Camera::render().
virtual void WorldInteractionInterface::loadWorld () pure virtual
Implemented in NetworkedWorldInteraction, and LocalWorldInteraction.
Referenced by Game::setup().
virtual void WorldInteractionInterface::movePlayerToCoordinate (int y, int x) pure virtual
Implemented in NetworkedWorldInteraction, and LocalWorldInteraction.
Referenced by Game::run().
The documentation for this class was generated from the following file:
WorldInteractionInterface.hpp