Trade App: Screen Class Reference
Screen Class Reference
Screen.
#include "Screen.hpp"
Classes
struct TextElement
Public Member Functions
Screen ()
void put (unsigned int colorPair, unsigned int layer, char c, int y, int x)
void put (TextElement c, int y, int x)
bool moveTo (int y, int x)
Move the internal cursor to x, y.
void clear ()
void render ()
int getHeight ()
int getWidth ()
Private Attributes
std::vector< std::vector< TextElement > > ScreenBuffer
int width
int height
int cursor_x
int cursor_y
Detailed Description
Screen.
Buffer and wrapper for ncurses screen in case this is to be ported to a system where ncurses is unavailable, or a gui is made.
Definition at line 13 of file Screen.hpp.
Constructor & Destructor Documentation
Screen::Screen ()
Definition at line 3 of file Screen.cpp.
References Screen::TextElement::c, Screen::TextElement::colorPair, cursor_x, cursor_y, height, Screen::TextElement::layer, ScreenBuffer, and width.
 {
     this->cursor_x = 0;
     this->cursor_y = 0;
     getmaxyx(stdscr, height, width);
     TextElement templ;
     templ.colorPair = 0;
     templ.layer = 0;
     templ.c = ' ';
     std::cout<<height<<width<<std::endl;
     for(unsigned int i = 0; i < height; ++i) {
         ScreenBuffer.push_back(std::vector< TextElement >());
         for(unsigned int j = 0; j < width; ++j) {
             ScreenBuffer[i].push_back(templ);
         }
     }
 }
Member Function Documentation
void Screen::clear ()
Definition at line 52 of file Screen.cpp.
References Screen::TextElement::c, Screen::TextElement::colorPair, height, Screen::TextElement::layer, ScreenBuffer, and width.
Referenced by Game::run().
 {
     TextElement templ;
     templ.colorPair = 0;
     templ.layer = 0;
     templ.c = ' ';
     for(unsigned int i = 0; i < height; ++i) {
         for(unsigned int j = 0; j < width; ++j) {
             ScreenBuffer[i][j] = templ;
         }
     }
 }
int Screen::getHeight ()
Definition at line 83 of file Screen.cpp.
References height.
Referenced by Player::draw(), and WorldChunk::draw().
 {
     return this->height;
 }
int Screen::getWidth ()
Definition at line 88 of file Screen.cpp.
References width.
Referenced by Player::draw(), and WorldChunk::draw().
 {
     return this->width;
 }
bool Screen::moveTo (int y, int x)
Move the internal cursor to x, y.
Parameters
int y
int x
Returns
bool success
Definition at line 41 of file Screen.cpp.
References cursor_x, and cursor_y.
 {
     if(y < height && y > 0 &&
         x < width && x > 0) {
         this->cursor_y = y;
         this->cursor_x = x;
         return true;
     }
     return false;
 }
void Screen::put (unsigned int colorPair, unsigned int layer, char c, int y, int x)
Definition at line 23 of file Screen.cpp.
References Screen::TextElement::c, Screen::TextElement::colorPair, and Screen::TextElement::layer.
Referenced by Player::draw(), and Tile::drawAt().
 {
     TextElement temp;
     temp.colorPair = colorPair;
     temp.layer = layer;
     temp.c = c;
     this->put(temp, y, x);
 }
void Screen::put (TextElement c, int y, int x)
Definition at line 32 of file Screen.cpp.
References Screen::TextElement::layer, and ScreenBuffer.
 {
     if(x < width && x > 0 && y < height && y > 0) {
         if(c.layer > ScreenBuffer[y][x].layer) {
             ScreenBuffer[y][x] = c;
         }
     }
 }
void Screen::render ()
Definition at line 67 of file Screen.cpp.
References height, ScreenBuffer, and width.
Referenced by Game::run().
 {
     unsigned int lastColorPair = 0;
     attrset(COLOR_PAIR(0));
     move(0, 0);
     for(int i = 0; i < height; ++i) {
         for(int j = 0; j < width; ++j) {
             if(ScreenBuffer[i][j].colorPair != lastColorPair) {
                 attrset(COLOR_PAIR(ScreenBuffer[i][j].colorPair));
                 lastColorPair = ScreenBuffer[i][j].colorPair;
             }
             addch(ScreenBuffer[i][j].c);
         }
     }
 }
Member Data Documentation
int Screen::cursor_x private
Definition at line 45 of file Screen.hpp.
Referenced by moveTo(), and Screen().
int Screen::cursor_y private
Definition at line 46 of file Screen.hpp.
Referenced by moveTo(), and Screen().
int Screen::height private
Definition at line 44 of file Screen.hpp.
Referenced by clear(), getHeight(), render(), and Screen().
std::vector< std::vector< TextElement > > Screen::ScreenBuffer private
Definition at line 42 of file Screen.hpp.
Referenced by clear(), put(), render(), and Screen().
int Screen::width private
Definition at line 43 of file Screen.hpp.
Referenced by clear(), getWidth(), render(), and Screen().
The documentation for this class was generated from the following files:
Screen.hpp
Screen.cpp