Arbitrage Simulator: Keymap Class Reference
Keymap Class Reference
#include "Keymap.hpp"
Public Member Functions
Keymap ()
void init ()
Input convert (int rawInput)
Private Member Functions
std::vector< std::pair< std::string, std::string > > loadFile ()
void createMap (std::vector< std::pair< std::string, std::string > > mappings)
Private Attributes
std::map< int, Input > inputMap
Static Private Attributes
static const std::string mapFile = "GameData/keymap.txt"
Detailed Description
Definition at line 14 of file Keymap.hpp.
Constructor & Destructor Documentation
Keymap::Keymap ()
Definition at line 5 of file Keymap.cpp.
References inputMap.
Member Function Documentation
Input Keymap::convert (int rawInput)
Definition at line 18 of file Keymap.cpp.
References IGNORED, and inputMap.
Referenced by Game::run().
void Keymap::createMap (std::vector< std::pair< std::string, std::string > > mappings) private
Definition at line 46 of file Keymap.cpp.
References inputMap, and InputMapping::toInput().
Referenced by init().
void Keymap::init ()
Definition at line 10 of file Keymap.cpp.
References createMap(), ESCAPE, inputMap, and loadFile().
Referenced by Game::setup().
std::vector< std::pair< std::string, std::string > > Keymap::loadFile () private
Definition at line 26 of file Keymap.cpp.
References mapFile.
Referenced by init().
Member Data Documentation
std::map<int, Input> Keymap::inputMap private
Definition at line 25 of file Keymap.hpp.
Referenced by convert(), createMap(), init(), and Keymap().
const std::string Keymap::mapFile = "GameData/keymap.txt" static private
Definition at line 21 of file Keymap.hpp.
Referenced by loadFile().
The documentation for this class was generated from the following files:
Keymap.hpp
Keymap.cpp