Arbitrage Simulator: NetworkedWorldInteraction Class Reference
NetworkedWorldInteraction Class Reference
Manager for networked world interaction.
#include "NetworkedWorldInteraction.hpp"
Public Member Functions
NetworkedWorldInteraction (std::string server, std::string port)
void loadWorld (boost::shared_ptr< Logger > logger)
void draw (Window::window_ptr window)
void draw (Window::window_ptr window, int playerY, int playerX)
void movePlayerToCoordinate (int y, int x)
Private Member Functions
void configure ()
bool hasChunkLoaded (int y, int x)
bool handShake ()
std::string checkVersion ()
int login ()
int fetchChunk (int chunkY, int chunkX)
Private Member Functions inherited from LocalWorldInteraction
LocalWorldInteraction ()
LocalWorldInteraction (std::string worldName)
bool chunkInWorld (int chunkY, int chunkX)
WorldChunk getChunk (int y, int x) const
void playerCoordinatesToChunkCoordinates (int &chunkY, int &chunkX, int &Y, int &X)
Convert the player's current global coordinates into a chunk, and coordinates in that chunk.
void globalCoordinatesToChunkCoordinates (int inY, int inX, int &chunkY, int &chunkX, int &outY, int &outX)
convert global coordinates to into a chunk, and coordinates in that chunk.
Private Attributes
std::string version
std::vector< std::pair< int, int > > chunksLoaded
Connection connection
Private Attributes inherited from LocalWorldInteraction
int playerX
int playerY
Generator generator
Detailed Description
Manager for networked world interaction.
: implement more graceful error handling : fetch world & worldChunk sizes from server : fetch worldChunks from server : send player movement notices to server : fetch city objects from server
Definition at line 35 of file NetworkedWorldInteraction.hpp.
Constructor & Destructor Documentation
NetworkedWorldInteraction::NetworkedWorldInteraction (std::string server, std::string port)
Definition at line 3 of file NetworkedWorldInteraction.cpp.
References chunksLoaded, configure(), Connection::connect(), connection, LocalWorldInteraction::playerX, and LocalWorldInteraction::playerY.
Member Function Documentation
std::string NetworkedWorldInteraction::checkVersion () private
Definition at line 88 of file NetworkedWorldInteraction.cpp.
References connection, Connection::read(), version, ServerSession::VERSION_CHECK, ServerSession::VERSION_CHECK_OK, ServerSession::VERSION_INCOMPATIBLE, and Connection::write().
Referenced by handShake().
void NetworkedWorldInteraction::configure () private
Definition at line 55 of file NetworkedWorldInteraction.cpp.
References ConfigLoader::getVersion(), ConfigLoader::load(), and version.
Referenced by NetworkedWorldInteraction().
void NetworkedWorldInteraction::draw (Window::window_ptr window) virtual
Reimplemented from LocalWorldInteraction.
Definition at line 20 of file NetworkedWorldInteraction.cpp.
References LocalWorldInteraction::playerX, and LocalWorldInteraction::playerY.
void NetworkedWorldInteraction::draw (Window::window_ptr window, int playerY, int playerX)
Definition at line 25 of file NetworkedWorldInteraction.cpp.
References World::chunks, and hasChunkLoaded().
int NetworkedWorldInteraction::fetchChunk (int chunkY, int chunkX) private
Definition at line 113 of file NetworkedWorldInteraction.cpp.
References World::chunks, chunksLoaded, connection, Connection::read(), ServerSession::REQUEST_CHUNK, ServerSession::REQUEST_OK, and Connection::write().
Referenced by movePlayerToCoordinate().
bool NetworkedWorldInteraction::handShake () private
Definition at line 71 of file NetworkedWorldInteraction.cpp.
References checkVersion(), and version.
Referenced by loadWorld().
bool NetworkedWorldInteraction::hasChunkLoaded (int y, int x) private
Definition at line 61 of file NetworkedWorldInteraction.cpp.
References chunksLoaded.
Referenced by draw(), and movePlayerToCoordinate().
void NetworkedWorldInteraction::loadWorld (boost::shared_ptr< Logger > logger) virtual
Reimplemented from LocalWorldInteraction.
Definition at line 12 of file NetworkedWorldInteraction.cpp.
References handShake().
int NetworkedWorldInteraction::login () private
Definition at line 107 of file NetworkedWorldInteraction.cpp.
References connection, ServerSession::LOGIN, and Connection::write().
void NetworkedWorldInteraction::movePlayerToCoordinate (int y, int x) virtual
Reimplemented from LocalWorldInteraction.
Definition at line 36 of file NetworkedWorldInteraction.cpp.
References LocalWorldInteraction::chunkInWorld(), fetchChunk(), hasChunkLoaded(), LocalWorldInteraction::playerCoordinatesToChunkCoordinates(), LocalWorldInteraction::playerX, and LocalWorldInteraction::playerY.
Member Data Documentation
std::vector< std::pair<int, int> > NetworkedWorldInteraction::chunksLoaded private
Definition at line 46 of file NetworkedWorldInteraction.hpp.
Referenced by fetchChunk(), hasChunkLoaded(), and NetworkedWorldInteraction().
Connection NetworkedWorldInteraction::connection private
Definition at line 52 of file NetworkedWorldInteraction.hpp.
Referenced by checkVersion(), fetchChunk(), login(), and NetworkedWorldInteraction().
std::string NetworkedWorldInteraction::version private
Definition at line 45 of file NetworkedWorldInteraction.hpp.
Referenced by checkVersion(), configure(), and handShake().
The documentation for this class was generated from the following files:
NetworkedWorldInteraction.hpp
NetworkedWorldInteraction.cpp