Trade App: WorldChunk Class Reference
WorldChunk Class Reference
#include "WorldChunk.hpp"
Public Member Functions
WorldChunk ()
WorldChunk (unsigned int top, unsigned int left)
WorldChunk (std::stringstream *ss)
void fromStringStream (std::stringstream *ss)
The stringstream structure expected into this is ObjectName objectData1, objectData2, ...
void toStringStream (std::stringstream *ss)
To String Stream.
void generateChunk (NoiseFunc *tileNoise, NoiseFunc *elevationNoise, NoiseFunc *elevationSkewNoise)
void draw (Screen &screen, int playerY, int playerX)
Static Public Member Functions
static void configure ()
static void setMaxYX (unsigned int y, unsigned int x)
static unsigned int getChunkWidth ()
static unsigned int getChunkHeight ()
static int getMaxCitiesPerChunk ()
Private Types
enum READ_STATE { object = 0, map = 1 }
Private Member Functions
bool doCullTile (int playerY, int playerX, int tileY, int tileX, int localTileI, int localTileJ)
void organizeTiles (std::vector< Tile > tiles)
float elevationMap (float input, float skew)
Static Private Member Functions
static void spawnCity (WorldChunk *self, std::stringstream *ss)
Private Attributes
unsigned int top
unsigned int left
std::vector< City > cities
std::vector< std::vector< Tile > > tiles
Static Private Attributes
static const std::string SpaceConstant = " "
static const std::string CityMarker = "city"
static const std::string MapMarker = "MAP"
static const int maxViewDistance = 10
static const bool cullingEnabled = true
static bool configured = false
static unsigned int chunk_height = 0
static unsigned int chunk_width = 0
static int max_cities_per_chunk = 0
static int maxX = 0
static int maxY = 0
static std::map< std::string, void(*)(WorldChunk *self, std::stringstream *ss)> factoryMap
Detailed Description
Definition at line 21 of file WorldChunk.hpp.
Member Enumeration Documentation
enum WorldChunk::READ_STATE private
Enumerator
object
map
Definition at line 68 of file WorldChunk.hpp.
                     {
         object = 0,
         map = 1
     };
Constructor & Destructor Documentation
WorldChunk::WorldChunk ()
Definition at line 20 of file WorldChunk.cpp.
References configure(), and configured.
 {
     if(!WorldChunk::configured) {
         this->configure();
     }
 }
WorldChunk::WorldChunk (unsigned int top, unsigned int left)
Definition at line 27 of file WorldChunk.cpp.
References chunk_height, chunk_width, configure(), and configured.
 {
     if(!WorldChunk::configured) {
         this->configure();
     }
     this->top = top * WorldChunk::chunk_height;
     this->left = left * WorldChunk::chunk_width;
 }
WorldChunk::WorldChunk (std::stringstream * ss)
Definition at line 36 of file WorldChunk.cpp.
References configure(), configured, and fromStringStream().
 {
     this->fromStringStream(ss);
     if(!WorldChunk::configured) {
         this->configure();
     }
 }
Member Function Documentation
void WorldChunk::configure () static
Definition at line 50 of file WorldChunk.cpp.
References chunk_height, chunk_width, configured, ConfigLoader::getIntOption(), and max_cities_per_chunk.
Referenced by Game::configure(), and WorldChunk().
 {
     WorldChunk::chunk_height = ConfigLoader::getIntOption("chunk_height", 30);
     WorldChunk::chunk_width = ConfigLoader::getIntOption("chunk_width", 30);
     WorldChunk::max_cities_per_chunk = ConfigLoader::getIntOption("max_cities_per_chunk", 5);
     WorldChunk::configured = true;
 }
bool WorldChunk::doCullTile (int playerY, int playerX, int tileY, int tileX, int localTileI, int localTileJ) private
Definition at line 174 of file WorldChunk.cpp.
References maxViewDistance.
Referenced by draw().
 {
     int diffY = playerY - tileY;
     int diffX = playerX - tileX;
     int distance = sqrt((diffY*diffY)+(diffX*diffX));
     if(distance < WorldChunk::maxViewDistance) {
         return false;
     } else {
         return true;
     }
 }
void WorldChunk::draw (Screen & screen, int playerY, int playerX)
Definition at line 156 of file WorldChunk.cpp.
References chunk_height, chunk_width, doCullTile(), Screen::getHeight(), Screen::getWidth(), left, Tile::setPallete(), tiles, and top.
 {
     int currX, currY;
     int halfHeight = screen.getHeight() / 2;
     int halfWidth = screen.getWidth() / 2;
     Tile::setPallete();
     for(unsigned int i = 0; i < WorldChunk::chunk_height; ++i) {
         for(unsigned int j = 0; j < WorldChunk::chunk_width; ++j) {
             this->tiles[i][j].drawAt(
                 screen,
                 (top + i - playerY) + halfHeight,
                 (left + j - playerX) + halfWidth,
                 this->doCullTile(playerY, playerX, top + i, left + j, i, j)
             );
         }
     }
 }
float WorldChunk::elevationMap (float input, float skew) private
Definition at line 264 of file WorldChunk.cpp.
Referenced by generateChunk().
 {
     float x = 1.0f - pow(2.00f, -(0.75f) * (input + 0.90));
     x += x*skew;
     return x;
 }
void WorldChunk::fromStringStream (std::stringstream * ss) virtual
The stringstream structure expected into this is ObjectName objectData1, objectData2, ...
ObjectName objectData1, objectData2, ... MAP 1 2 3 4 2 3 1 2 3 1 ...
Implements AbstractGameObject.
Definition at line 58 of file WorldChunk.cpp.
References chunk_height, chunk_width, factoryMap, left, map, object, organizeTiles(), and top.
Referenced by WorldChunk().
 {
     READ_STATE readState = object;
     std::vector<Tile> tilesToSpawn;
     std::string nextObject;
     (*ss)>>top>>left;
     while( ss->good() &&
          tilesToSpawn.size() < WorldChunk::chunk_height * WorldChunk::chunk_width
     ) {
         if(readState == object) {
             (*ss)>>nextObject;
             if( this->factoryMap.find(nextObject) != this->factoryMap.end() ) {
                 this->factoryMap[nextObject](this, ss);
             } else if( nextObject == "MAP" ) {
                 readState = map;
                 tilesToSpawn.push_back(Tile(ss));
             }
         } else if(readState == map) {
             tilesToSpawn.push_back(Tile(ss));
         }
     }
     this->organizeTiles(tilesToSpawn);
 }
void WorldChunk::generateChunk (NoiseFunc * tileNoise, NoiseFunc * elevationNoise, NoiseFunc * elevationSkewNoise)
Definition at line 98 of file WorldChunk.cpp.
References chunk_height, chunk_width, cities, City::city_name_ends, City::city_name_starts, elevationMap(), NoiseFunc::get(), left, max_cities_per_chunk, Tile::randomSpawn(), tiles, and top.
Referenced by World::prepareChunk().
 {
     this->cities.clear();
     this->tiles.clear();
     //@todo: base this off of a noise function rather than rand
     for(unsigned int i = 0; i < WorldChunk::chunk_height; ++i) {
         this->tiles.push_back(std::vector<Tile>());
         for( unsigned int j = 0; j < WorldChunk::chunk_width; ++j) {
             this->tiles[i].push_back(Tile::randomSpawn(
                 tileNoise->get(this->top + i, this->left + j),
                 this->elevationMap(
                     elevationNoise->get(this->top + i, this->left + j),
                     elevationSkewNoise->get(this->top + i, this->left + j)
                 )
             ));
         }
     }
     int num_cities = rand() % WorldChunk::max_cities_per_chunk;
     //@todo: make sure no two cities spawn on or near eachother
     for(unsigned int i = 0; i < num_cities; ++i) {
         std::string cityName =
             City::city_name_starts[rand() % City::city_name_starts.size()]
             + City::city_name_ends[rand() % City::city_name_ends.size()]
         ;
         this->cities.push_back(City(cityName, rand() % WorldChunk::chunk_height, rand() % WorldChunk::chunk_width));
     }
     for(unsigned int i = 0;  i < cities.size(); ++i) {
         unsigned int x, y;
         x = cities[i].getPosX();
         y = cities[i].getPosY();
        tiles[y][x].convertToCity();
     }
 }
unsigned int WorldChunk::getChunkHeight () static
Definition at line 276 of file WorldChunk.cpp.
References chunk_height.
Referenced by World::generateWorld().
 {
     return WorldChunk::chunk_height;
 }
unsigned int WorldChunk::getChunkWidth () static
Definition at line 271 of file WorldChunk.cpp.
References chunk_width.
Referenced by World::generateWorld().
 {
     return WorldChunk::chunk_width;
 }
int WorldChunk::getMaxCitiesPerChunk () static
Definition at line 281 of file WorldChunk.cpp.
References max_cities_per_chunk.
 {
     return WorldChunk::max_cities_per_chunk;
 }
void WorldChunk::organizeTiles (std::vector< Tile > tiles) private
Definition at line 145 of file WorldChunk.cpp.
References chunk_height, and chunk_width.
Referenced by fromStringStream().
 {
     for(unsigned int i = 0; i < WorldChunk::chunk_height; ++i) {
         this->tiles.push_back(std::vector<Tile>());
         for( unsigned int j = 0; j < WorldChunk::chunk_width; ++j) {
             this->tiles[i].push_back(tiles[(i*WorldChunk::chunk_height) + j]);
         }
     }
 }
void WorldChunk::setMaxYX (unsigned int y, unsigned int x) static
Definition at line 44 of file WorldChunk.cpp.
References maxX, and maxY.
Referenced by Game::configure().
 {
     WorldChunk::maxY = y;
     WorldChunk::maxX = x;
 }
void WorldChunk::spawnCity (WorldChunk * self, std::stringstream * ss) static private
Definition at line 140 of file WorldChunk.cpp.
 {
     self->cities.push_back(City(ss));
 }
void WorldChunk::toStringStream (std::stringstream * ss) virtual
To String Stream.
Add this object's state into the stringstream at the current point in the stream.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 82 of file WorldChunk.cpp.
References cities, CityMarker, left, MapMarker, SpaceConstant, tiles, and top.
 {
     (*ss)<<top<<" "<<left;
     for(unsigned int i = 0; i < this->cities.size(); ++i) {
         (*ss)<<WorldChunk::CityMarker<<WorldChunk::SpaceConstant;
         this->cities[i].toStringStream(ss);
     }
     (*ss)<<WorldChunk::MapMarker<<WorldChunk::SpaceConstant;
     for(unsigned int i = 0; i < this->tiles.size(); ++i) {
         for(unsigned int j = 0; j < this->tiles[i].size(); ++j) {
             this->tiles[i][j].toStringStream(ss);
             (*ss)<<SpaceConstant;
         }
     }
 }
Member Data Documentation
unsigned int WorldChunk::chunk_height = 0 static private
Definition at line 60 of file WorldChunk.hpp.
Referenced by configure(), draw(), fromStringStream(), generateChunk(), getChunkHeight(), organizeTiles(), and WorldChunk().
unsigned int WorldChunk::chunk_width = 0 static private
Definition at line 61 of file WorldChunk.hpp.
Referenced by configure(), draw(), fromStringStream(), generateChunk(), getChunkWidth(), organizeTiles(), and WorldChunk().
std::vector<City> WorldChunk::cities private
Definition at line 87 of file WorldChunk.hpp.
Referenced by generateChunk(), and toStringStream().
const std::string WorldChunk::CityMarker = "city" static private
Definition at line 54 of file WorldChunk.hpp.
Referenced by toStringStream().
bool WorldChunk::configured = false static private
Definition at line 59 of file WorldChunk.hpp.
Referenced by configure(), and WorldChunk().
const bool WorldChunk::cullingEnabled = true static private
Definition at line 57 of file WorldChunk.hpp.
std::map< std::string, void(*)(WorldChunk *self, std::stringstream *ss)> WorldChunk::factoryMap static private
Initial value:
=
    {
        {WorldChunk::CityMarker, spawnCity}
    }
Definition at line 76 of file WorldChunk.hpp.
Referenced by fromStringStream().
unsigned int WorldChunk::left private
Definition at line 86 of file WorldChunk.hpp.
Referenced by draw(), fromStringStream(), generateChunk(), and toStringStream().
const std::string WorldChunk::MapMarker = "MAP" static private
Definition at line 55 of file WorldChunk.hpp.
Referenced by toStringStream().
int WorldChunk::max_cities_per_chunk = 0 static private
Definition at line 62 of file WorldChunk.hpp.
Referenced by configure(), generateChunk(), and getMaxCitiesPerChunk().
const int WorldChunk::maxViewDistance = 10 static private
Definition at line 56 of file WorldChunk.hpp.
Referenced by doCullTile().
int WorldChunk::maxX = 0 static private
Definition at line 65 of file WorldChunk.hpp.
Referenced by setMaxYX().
int WorldChunk::maxY = 0 static private
Definition at line 66 of file WorldChunk.hpp.
Referenced by setMaxYX().
const std::string WorldChunk::SpaceConstant = " " static private
Definition at line 53 of file WorldChunk.hpp.
Referenced by toStringStream().
std::vector< std::vector<Tile> > WorldChunk::tiles private
Definition at line 88 of file WorldChunk.hpp.
Referenced by draw(), generateChunk(), and toStringStream().
unsigned int WorldChunk::top private
Definition at line 85 of file WorldChunk.hpp.
Referenced by draw(), fromStringStream(), generateChunk(), and toStringStream().
The documentation for this class was generated from the following files:
WorldChunk.hpp
WorldChunk.cpp