Arbitrage Simulator: ConsoleLogger Class Reference
ConsoleLogger Class Reference
#include "ConsoleLogger.hpp"
Public Member Functions
ConsoleLogger ()
virtual ~ConsoleLogger ()
virtual void debug (const char *fmt,...)
virtual void info (const char *fmt,...)
virtual void warn (const char *fmt,...)
virtual void error (const char *fmt,...)
virtual void log (Logger::LogLevel level, const char *fmt,...)
Public Member Functions inherited from Logger
virtual ~Logger ()
Protected Member Functions
virtual void print (Logger::LogLevel level, const char *fmt, va_list args)
Protected Member Functions inherited from Logger
virtual std::string format_string (LogLevel level, const char *fmt, va_list args)
std::string get_time ()
Additional Inherited Members
Public Types inherited from Logger
enum LogLevel {
NONE = 0, DEBUG = 1, INFO = 2, WARN = 3,
ERROR = 4
}
typedef boost::shared_ptr< Logger > LoggerPtr
Static Public Member Functions inherited from Logger
static void configure ()
Static Protected Attributes inherited from Logger
static const std::string levelStrings [4]
static int logLevel = 0
Detailed Description
Definition at line 10 of file ConsoleLogger.hpp.
Constructor & Destructor Documentation
ConsoleLogger::ConsoleLogger ()
Definition at line 3 of file ConsoleLogger.cpp.
ConsoleLogger::~ConsoleLogger () virtual
Definition at line 8 of file ConsoleLogger.cpp.
Member Function Documentation
void ConsoleLogger::debug (const char * fmt, ...) virtual
Implements Logger.
Definition at line 13 of file ConsoleLogger.cpp.
References Logger::DEBUG, and print().
void ConsoleLogger::error (const char * fmt, ...) virtual
Implements Logger.
Definition at line 37 of file ConsoleLogger.cpp.
References Logger::ERROR, and print().
void ConsoleLogger::info (const char * fmt, ...) virtual
Implements Logger.
Definition at line 21 of file ConsoleLogger.cpp.
References Logger::INFO, and print().
void ConsoleLogger::log (Logger::LogLevel level, const char * fmt, ...) virtual
Implements Logger.
Definition at line 46 of file ConsoleLogger.cpp.
References print().
void ConsoleLogger::print (Logger::LogLevel level, const char * fmt, va_list args) protected virtual
Definition at line 54 of file ConsoleLogger.cpp.
References Logger::format_string(), and Logger::logLevel.
Referenced by debug(), error(), info(), log(), and warn().
void ConsoleLogger::warn (const char * fmt, ...) virtual
Implements Logger.
Definition at line 29 of file ConsoleLogger.cpp.
References print(), and Logger::WARN.
The documentation for this class was generated from the following files:
ConsoleLogger.hpp
ConsoleLogger.cpp