Arbitrage Simulator: AbstractPass Class Reference
AbstractPass Class Reference abstract
Abstract world pass.
#include "AbstractPass.hpp"
Public Member Functions
virtual void init ()
virtual void execute (World *world, boost::shared_ptr< Logger > logger)
virtual AbstractPass * clone ()=0
virtual std::string getName ()=0
Protected Member Functions
virtual void executeChunk (int top, int left, WorldChunk *chunk)
virtual void doTile (int i, int j, Tile *tile)=0
Detailed Description
Abstract world pass.
A root interface for all world generation passes to follow.
Definition at line 17 of file AbstractPass.hpp.
Member Function Documentation
virtual AbstractPass* AbstractPass::clone () pure virtual
Implemented in CityPass, TypePass, and ElevationPass.
Referenced by init().
virtual void AbstractPass::doTile (int i, int j, Tile * tile) protected pure virtual
Implemented in CityPass, TypePass, and ElevationPass.
Referenced by executeChunk(), and init().
void AbstractPass::execute (World * world, boost::shared_ptr< Logger > logger) virtual
Reimplemented in CityPass.
Definition at line 3 of file AbstractPass.cpp.
References World::chunks, and executeChunk().
Referenced by CityPass::execute(), and init().
void AbstractPass::executeChunk (int top, int left, WorldChunk * chunk) protected virtual
Definition at line 13 of file AbstractPass.cpp.
References doTile(), WorldChunk::getChunkHeight(), WorldChunk::getChunkWidth(), and WorldChunk::tiles.
Referenced by execute(), and init().
virtual std::string AbstractPass::getName () pure virtual
Implemented in CityPass, TypePass, and ElevationPass.
Referenced by init().
virtual void AbstractPass::init () inline virtual
Reimplemented in CityPass, TypePass, and ElevationPass.
Definition at line 20 of file AbstractPass.hpp.
References clone(), doTile(), execute(), executeChunk(), and getName().
The documentation for this class was generated from the following files:
AbstractPass.hpp
AbstractPass.cpp