Arbitrage Simulator: LocalWorldInteraction Class Reference
LocalWorldInteraction Class Reference
Manager for non-networked world interaction.
#include "LocalWorldInteraction.hpp"
Public Member Functions
LocalWorldInteraction ()
LocalWorldInteraction (std::string worldName)
void loadWorld (boost::shared_ptr< Logger > logger)
void draw (Window::window_ptr window)
void movePlayerToCoordinate (int y, int x)
Tile getTileUnderPlayer ()
City getCity (int y, int x)
bool chunkInWorld (int chunkY, int chunkX)
WorldChunk getChunk (int y, int x) const
Protected Member Functions
void playerCoordinatesToChunkCoordinates (int &chunkY, int &chunkX, int &Y, int &X)
Convert the player's current global coordinates into a chunk, and coordinates in that chunk.
void globalCoordinatesToChunkCoordinates (int inY, int inX, int &chunkY, int &chunkX, int &outY, int &outX)
convert global coordinates to into a chunk, and coordinates in that chunk.
Protected Member Functions inherited from World
void init ()
Initialize.
void spawnChunk (int y, int x)
Spawn a chunk at x,y.
WorldChunk prepareChunk (int y, int x)
Prepare Chunk.
World ()
World (std::stringstream *ss)
World (std::string name)
void fromStringStream (std::stringstream *ss)
void toStringStream (std::stringstream *ss)
void generateWorld ()
void draw (Window::window_ptr window, int playerY, int playerX)
Protected Attributes
int playerX
int playerY
Generator generator
Protected Attributes inherited from World
int chunkHeight
int chunkWidth
std::vector< std::vector< WorldChunk > > chunks
std::string name
time_t creationTimestamp
Additional Inherited Members
Static Protected Member Functions inherited from World
static void configure ()
static int getWorldHeight ()
static int getWorldWidth ()
Static Protected Attributes inherited from World
static unsigned int worldHeight = 0
static unsigned int worldWidth = 0
Detailed Description
Manager for non-networked world interaction.
Definition at line 19 of file LocalWorldInteraction.hpp.
Constructor & Destructor Documentation
LocalWorldInteraction::LocalWorldInteraction ()
Definition at line 3 of file LocalWorldInteraction.cpp.
References Generator::DefaultGenerator(), generator, playerX, and playerY.
LocalWorldInteraction::LocalWorldInteraction (std::string worldName)
Definition at line 10 of file LocalWorldInteraction.cpp.
References Generator::DefaultGenerator(), generator, playerX, and playerY.
Member Function Documentation
bool LocalWorldInteraction::chunkInWorld (int chunkY, int chunkX)
Definition at line 76 of file LocalWorldInteraction.cpp.
References World::getWorldHeight(), and World::getWorldWidth().
Referenced by NetworkedWorldInteraction::movePlayerToCoordinate().
void LocalWorldInteraction::draw (Window::window_ptr window) virtual
Implements WorldInteractionInterface.
Reimplemented in NetworkedWorldInteraction.
Definition at line 24 of file LocalWorldInteraction.cpp.
References World::draw(), playerX, and playerY.
WorldChunk LocalWorldInteraction::getChunk (int y, int x) const
Definition at line 87 of file LocalWorldInteraction.cpp.
References World::chunks.
City LocalWorldInteraction::getCity (int y, int x) virtual
Implements WorldInteractionInterface.
Reimplemented in NetworkedWorldInteraction.
Definition at line 42 of file LocalWorldInteraction.cpp.
References World::chunks, and globalCoordinatesToChunkCoordinates().
Tile LocalWorldInteraction::getTileUnderPlayer () virtual
Implements WorldInteractionInterface.
Definition at line 35 of file LocalWorldInteraction.cpp.
References World::chunks, and playerCoordinatesToChunkCoordinates().
void LocalWorldInteraction::globalCoordinatesToChunkCoordinates (int inY, int inX, int & chunkY, int & chunkX, int & outY, int & outX) protected
convert global coordinates to into a chunk, and coordinates in that chunk.
Parameters
int inY
int inX
int &chunkY
int &chunkX
int &outY
int &outX
Definition at line 64 of file LocalWorldInteraction.cpp.
References World::chunkHeight, and World::chunkWidth.
Referenced by getCity(), NetworkedWorldInteraction::getCity(), and playerCoordinatesToChunkCoordinates().
void LocalWorldInteraction::loadWorld (boost::shared_ptr< Logger > logger) virtual
Implements WorldInteractionInterface.
Reimplemented in NetworkedWorldInteraction.
Definition at line 17 of file LocalWorldInteraction.cpp.
References Generator::execute(), World::generateWorld(), and generator.
void LocalWorldInteraction::movePlayerToCoordinate (int y, int x) virtual
Implements WorldInteractionInterface.
Reimplemented in NetworkedWorldInteraction.
Definition at line 29 of file LocalWorldInteraction.cpp.
References playerX, and playerY.
void LocalWorldInteraction::playerCoordinatesToChunkCoordinates (int & chunkY, int & chunkX, int & Y, int & X) protected
Convert the player's current global coordinates into a chunk, and coordinates in that chunk.
Parameters
int &chunkY
int &chunkX
int &Y
int &X
Definition at line 53 of file LocalWorldInteraction.cpp.
References globalCoordinatesToChunkCoordinates(), playerX, and playerY.
Referenced by getTileUnderPlayer(), and NetworkedWorldInteraction::movePlayerToCoordinate().
Member Data Documentation
Generator LocalWorldInteraction::generator protected
Definition at line 39 of file LocalWorldInteraction.hpp.
Referenced by loadWorld(), and LocalWorldInteraction().
int LocalWorldInteraction::playerX protected
Definition at line 36 of file LocalWorldInteraction.hpp.
Referenced by draw(), NetworkedWorldInteraction::draw(), LocalWorldInteraction(), movePlayerToCoordinate(), NetworkedWorldInteraction::movePlayerToCoordinate(), NetworkedWorldInteraction::NetworkedWorldInteraction(), and playerCoordinatesToChunkCoordinates().
int LocalWorldInteraction::playerY protected
Definition at line 37 of file LocalWorldInteraction.hpp.
Referenced by draw(), NetworkedWorldInteraction::draw(), LocalWorldInteraction(), movePlayerToCoordinate(), NetworkedWorldInteraction::movePlayerToCoordinate(), NetworkedWorldInteraction::NetworkedWorldInteraction(), and playerCoordinatesToChunkCoordinates().
The documentation for this class was generated from the following files:
LocalWorldInteraction.hpp
LocalWorldInteraction.cpp