Arbitrage Simulator: City Class Reference
City Class Reference
City Game Object.
#include "City.hpp"
Public Member Functions
City ()
City (const City &other)
City (std::stringstream *ss)
City (std::string name, int pos_x, int pos_y)
void fromStringStream (std::stringstream *ss)
From String Stream.
void toStringStream (std::stringstream *ss)
To String Stream.
void setName (std::string name)
const std::string & getName () const
void setPosX (int x)
int getPosX () const
void setPosY (int y)
int getPosY () const
void addToInventory (int itemId, int count)
Inventory getInventory ()
Static Public Member Functions
static void load_city_names ()
Load City Names.
Static Public Attributes
static std::vector< std::string > city_name_starts = std::vector<std::string>()
static std::vector< std::string > city_name_ends = std::vector<std::string>()
Private Attributes
std::string name
int pos_x
int pos_y
Inventory inv
Static Private Attributes
static const std::string city_name_file_path = "GameData/city_names.txt"
std::string city_name_file_path the place on disk to find a file full of city name starts and ends.
Detailed Description
City Game Object.
The city game object is for managing trading hubs. Each city exists at a point in the world and owns and maintains the information necessary to facilitate a local economy.
Definition at line 19 of file City.hpp.
Constructor & Destructor Documentation
City::City ()
Definition at line 8 of file City.cpp.
References inv, name, pos_x, and pos_y.
City::City (const City & other)
Definition at line 16 of file City.cpp.
References inv, name, pos_x, and pos_y.
City::City (std::stringstream * ss)
Definition at line 32 of file City.cpp.
References fromStringStream(), inv, name, pos_x, and pos_y.
City::City (std::string name, int pos_x, int pos_y)
Definition at line 24 of file City.cpp.
References inv, name, pos_x, and pos_y.
Member Function Documentation
void City::addToInventory (int itemId, int count)
Definition at line 98 of file City.cpp.
References Inventory::add(), and inv.
Referenced by CityPass::convertTileToCity().
void City::fromStringStream (std::stringstream * ss) virtual
From String Stream.
Assume this object is the next object in the stringstream and restore it's own state based on the stringstream's contents.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 41 of file City.cpp.
References Globals::file_delimiter, Inventory::fromStringStream(), inv, name, Globals::object_delimiter, pos_x, and pos_y.
Referenced by City().
Inventory City::getInventory ()
Definition at line 103 of file City.cpp.
References inv.
Referenced by GameState::CityInventory::getCityInventory().
const std::string & City::getName () const
Definition at line 73 of file City.cpp.
References name.
Referenced by GameState::Playing::update().
int City::getPosX () const
Definition at line 83 of file City.cpp.
References pos_x.
int City::getPosY () const
Definition at line 93 of file City.cpp.
References pos_y.
void City::load_city_names () static
Load City Names.
City names will exist within a file at city_name_file_path. Load this from the disk so that users can generate their own set of possible names.
Definition at line 108 of file City.cpp.
References city_name_ends, city_name_file_path, city_name_starts, and name.
Referenced by Server::configure(), and Game::configure().
void City::setName (std::string name)
Definition at line 68 of file City.cpp.
References name.
void City::setPosX (int x)
Definition at line 78 of file City.cpp.
References pos_x.
void City::setPosY (int y)
Definition at line 88 of file City.cpp.
References pos_y.
void City::toStringStream (std::stringstream * ss) virtual
To String Stream.
Add this object's state into the stringstream at the current point in the stream.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 60 of file City.cpp.
References Globals::file_delimiter, inv, name, Globals::object_delimiter, pos_x, pos_y, and Inventory::toStringStream().
Member Data Documentation
std::vector< std::string > City::city_name_ends = std::vector<std::string>() static
Definition at line 49 of file City.hpp.
Referenced by CityPass::convertTileToCity(), and load_city_names().
const std::string City::city_name_file_path = "GameData/city_names.txt" static private
std::string city_name_file_path the place on disk to find a file full of city name starts and ends.
Definition at line 51 of file City.hpp.
Referenced by load_city_names().
std::vector< std::string > City::city_name_starts = std::vector<std::string>() static
Definition at line 48 of file City.hpp.
Referenced by CityPass::convertTileToCity(), and load_city_names().
Inventory City::inv private
Definition at line 60 of file City.hpp.
Referenced by addToInventory(), City(), fromStringStream(), getInventory(), and toStringStream().
std::string City::name private
Definition at line 56 of file City.hpp.
Referenced by City(), fromStringStream(), getName(), load_city_names(), setName(), and toStringStream().
int City::pos_x private
Definition at line 57 of file City.hpp.
Referenced by City(), fromStringStream(), getPosX(), setPosX(), and toStringStream().
int City::pos_y private
Definition at line 58 of file City.hpp.
Referenced by City(), fromStringStream(), getPosY(), setPosY(), and toStringStream().
The documentation for this class was generated from the following files:
City.hpp
City.cpp