Arbitrage Simulator: GameState::State Class Reference
GameState::State Class Reference abstract
#include "State.hpp"
Public Member Functions
virtual void init ()=0
virtual void setLogger (Logger::LoggerPtr logger)
virtual void update (WorldInteractionInterface *worldProxy, Input input)=0
virtual void render (WorldInteractionInterface *worldProxy, Window::window_ptr window)=0
virtual State * nextState ()=0
virtual void clearNextState ()=0
virtual bool shouldClose ()=0
virtual int passDown ()
virtual int passUp ()
virtual void recvDown (int msg)
virtual void recvUp (int msg)
Protected Attributes
Logger::LoggerPtr logger
int msgDown
int msgUp
int recvMsgDown
int recvMsgUp
Detailed Description
Definition at line 11 of file State.hpp.
Member Function Documentation
virtual void GameState::State::clearNextState () pure virtual
Implemented in GameState::Menu, and GameState::Playing.
Referenced by Game::run().
virtual void GameState::State::init () pure virtual
Implemented in GameState::Menu, and GameState::Playing.
virtual State* GameState::State::nextState () pure virtual
Implemented in GameState::Menu, and GameState::Playing.
Referenced by Game::run().
int GameState::State::passDown () virtual
Definition at line 8 of file State.cpp.
References msgDown.
Referenced by Game::run().
int GameState::State::passUp () virtual
Definition at line 12 of file State.cpp.
References msgUp.
void GameState::State::recvDown (int msg) virtual
Definition at line 16 of file State.cpp.
References recvMsgDown.
Referenced by Game::run().
void GameState::State::recvUp (int msg) virtual
Definition at line 20 of file State.cpp.
References recvMsgUp.
virtual void GameState::State::render (WorldInteractionInterface * worldProxy, Window::window_ptr window) pure virtual
Implemented in GameState::Menu, and GameState::Playing.
void GameState::State::setLogger (Logger::LoggerPtr logger) virtual
Definition at line 3 of file State.cpp.
References logger.
Referenced by Game::run().
virtual bool GameState::State::shouldClose () pure virtual
Implemented in GameState::Menu, and GameState::Playing.
virtual void GameState::State::update (WorldInteractionInterface * worldProxy, Input input) pure virtual
Implemented in GameState::Menu, and GameState::Playing.
Member Data Documentation
Logger::LoggerPtr GameState::State::logger protected
Definition at line 26 of file State.hpp.
Referenced by GameState::Playing::init(), GameState::Menu::Menu(), setLogger(), and GameState::Menu::update().
int GameState::State::msgDown protected
Definition at line 27 of file State.hpp.
Referenced by passDown(), and GameState::Menu::update().
int GameState::State::msgUp protected
Definition at line 28 of file State.hpp.
Referenced by passUp().
int GameState::State::recvMsgDown protected
Definition at line 29 of file State.hpp.
Referenced by recvDown().
int GameState::State::recvMsgUp protected
Definition at line 30 of file State.hpp.
Referenced by recvUp().
The documentation for this class was generated from the following files:
State.hpp
State.cpp