Arbitrage Simulator: GameState::CityInventory Class Reference
GameState::CityInventory Class Reference
#include "CityInventory.hpp"
Public Member Functions
CityInventory ()
~CityInventory ()
void init ()
void setCity (City city)
void update (WorldInteractionInterface *worldProxy, Context *ctx)
void render (WorldInteractionInterface *worldProxy, Window::window_ptr window)
State * nextState ()
void clearNextState ()
bool shouldClose ()
Public Member Functions inherited from GameState::State
virtual void setLogger (Logger::LoggerPtr logger)
virtual int passDown ()
virtual int passUp ()
virtual void recvDown (int msg)
virtual void recvUp (int msg)
Private Member Functions
void getCityInventory (City *city)
void populateMenu (Component::Menu *menu, std::vector< std::string > options)
Private Attributes
City city
std::vector< std::string > options
std::vector< Inventory::Record > cityInventory
std::vector< std::string > cityInventoryOptions
bool inventoryShouldClose
Component::Menu inventory
Additional Inherited Members
Protected Attributes inherited from GameState::State
Logger::LoggerPtr logger
int msgDown
int msgUp
int recvMsgDown
int recvMsgUp
Detailed Description
Definition at line 13 of file CityInventory.hpp.
Constructor & Destructor Documentation
GameState::CityInventory::CityInventory ()
Definition at line 3 of file CityInventory.cpp.
References GameState::State::logger.
GameState::CityInventory::~CityInventory ()
Definition at line 8 of file CityInventory.cpp.
Member Function Documentation
void GameState::CityInventory::clearNextState () virtual
Implements GameState::State.
Definition at line 65 of file CityInventory.cpp.
void GameState::CityInventory::getCityInventory (City * city) private
Definition at line 75 of file CityInventory.cpp.
References cityInventory, cityInventoryOptions, ItemMap::get(), Item::getBaseWorth(), Item::getDescription(), Inventory::getInv(), City::getInventory(), Item::getName(), and Item::getWeight().
Referenced by init(), and setCity().
void GameState::CityInventory::init () virtual
Implements GameState::State.
Definition at line 13 of file CityInventory.cpp.
References city, cityInventoryOptions, getCityInventory(), inventory, inventoryShouldClose, options, and populateMenu().
Referenced by GameState::Playing::update().
GameState::State * GameState::CityInventory::nextState () virtual
Implements GameState::State.
Definition at line 60 of file CityInventory.cpp.
void GameState::CityInventory::populateMenu (Component::Menu * menu, std::vector< std::string > options) private
Definition at line 101 of file CityInventory.cpp.
References inventory.
Referenced by init(), and setCity().
void GameState::CityInventory::render (WorldInteractionInterface * worldProxy, Window::window_ptr window) virtual
Implements GameState::State.
Definition at line 47 of file CityInventory.cpp.
References inventory, Component::Menu::render(), and Component::Menu::setDims().
void GameState::CityInventory::setCity (City city)
Definition at line 21 of file CityInventory.cpp.
References city, cityInventoryOptions, getCityInventory(), inventory, and populateMenu().
Referenced by GameState::Playing::update().
bool GameState::CityInventory::shouldClose () virtual
Implements GameState::State.
Definition at line 70 of file CityInventory.cpp.
References inventoryShouldClose.
void GameState::CityInventory::update (WorldInteractionInterface * worldProxy, Context * ctx) virtual
Implements GameState::State.
Definition at line 28 of file CityInventory.cpp.
References inventory, inventoryShouldClose, GameState::State::logger, GameState::State::msgDown, and Component::Menu::update().
Member Data Documentation
City GameState::CityInventory::city private
Definition at line 26 of file CityInventory.hpp.
Referenced by init(), and setCity().
std::vector<Inventory::Record> GameState::CityInventory::cityInventory private
Definition at line 28 of file CityInventory.hpp.
Referenced by getCityInventory().
std::vector<std::string> GameState::CityInventory::cityInventoryOptions private
Definition at line 29 of file CityInventory.hpp.
Referenced by getCityInventory(), init(), and setCity().
Component::Menu GameState::CityInventory::inventory private
Definition at line 35 of file CityInventory.hpp.
Referenced by init(), populateMenu(), render(), setCity(), and update().
bool GameState::CityInventory::inventoryShouldClose private
Definition at line 34 of file CityInventory.hpp.
Referenced by init(), shouldClose(), and update().
std::vector<std::string> GameState::CityInventory::options private
Definition at line 27 of file CityInventory.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
CityInventory.hpp
CityInventory.cpp