Arbitrage Simulator: Inventory Class Reference
Inventory Class Reference
#include "Inventory.hpp"
Classes
struct Record
Public Member Functions
Inventory ()
Inventory (const Inventory &other)
Inventory (std::stringstream *ss)
void fromStringStream (std::stringstream *ss)
From String Stream.
void toStringStream (std::stringstream *ss)
To String Stream.
void add (int itemId, int count)
void add (Item item, int count)
Record get (int itemId)
std::vector< Record > getInv ()
Private Member Functions
int find (int itemId)
Private Attributes
std::vector< Record > inv
Detailed Description
Definition at line 14 of file Inventory.hpp.
Constructor & Destructor Documentation
Inventory::Inventory ()
Definition at line 3 of file Inventory.cpp.
References inv.
Referenced by Inventory::Record::Record().
Inventory::Inventory (const Inventory & other)
Definition at line 8 of file Inventory.cpp.
References inv.
Inventory::Inventory (std::stringstream * ss)
Definition at line 16 of file Inventory.cpp.
References fromStringStream(), and inv.
Member Function Documentation
void Inventory::add (int itemId, int count)
Definition at line 58 of file Inventory.cpp.
References find(), and inv.
Referenced by add(), City::addToInventory(), and Inventory::Record::Record().
void Inventory::add (Item item, int count)
Definition at line 68 of file Inventory.cpp.
References add(), and Item::getId().
int Inventory::find (int itemId) private
Definition at line 87 of file Inventory.cpp.
References inv.
Referenced by add(), get(), and Inventory::Record::Record().
void Inventory::fromStringStream (std::stringstream * ss) virtual
From String Stream.
Assume this object is the next object in the stringstream and restore it's own state based on the stringstream's contents.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 22 of file Inventory.cpp.
References Globals::file_delimiter, inv, and Globals::object_delimiter.
Referenced by City::fromStringStream(), Inventory(), and Inventory::Record::Record().
Inventory::Record Inventory::get (int itemId)
Definition at line 73 of file Inventory.cpp.
References find(), and inv.
std::vector< Inventory::Record > Inventory::getInv ()
Definition at line 82 of file Inventory.cpp.
References inv.
Referenced by GameState::CityInventory::getCityInventory(), and Inventory::Record::Record().
void Inventory::toStringStream (std::stringstream * ss) virtual
To String Stream.
Add this object's state into the stringstream at the current point in the stream.
Parameters
std::stringstream *ss
Implements AbstractGameObject.
Definition at line 49 of file Inventory.cpp.
References Globals::file_delimiter, inv, and Globals::object_delimiter.
Referenced by Inventory::Record::Record(), and City::toStringStream().
Member Data Documentation
std::vector<Record> Inventory::inv private
Definition at line 39 of file Inventory.hpp.
Referenced by add(), find(), fromStringStream(), get(), getInv(), Inventory(), and toStringStream().
The documentation for this class was generated from the following files:
Inventory.hpp
Inventory.cpp