Arbitrage Simulator: ConsoleWindow Class Reference
ConsoleWindow Class Reference
ConsoleWindow.
#include "ConsoleWindow.hpp"
Public Member Functions
ConsoleWindow ()
virtual ~ConsoleWindow ()
virtual void render ()
BufferLogger * getLogger ()
Public Member Functions inherited from CursesWindow
CursesWindow ()
CursesWindow (int y, int x, int height, int width)
virtual ~CursesWindow ()
virtual void init ()
virtual void putstr (int y, int x, std::string str, int color=0)
virtual void put (unsigned int colorPair, unsigned int layer, char c, int y, int x)
virtual void put (TextElement c, int y, int x)
virtual void clear ()
virtual void resize (int height, int width)
virtual void move (int y, int x)
virtual int getCh ()
virtual int getY ()
virtual int getX ()
virtual int getHeight ()
virtual int getWidth ()
Public Member Functions inherited from Window
virtual ~Window ()
Static Public Member Functions
static void setPallete ()
Static Private Member Functions
static void initColorPallete ()
Private Attributes
BufferLogger logger
Static Private Attributes
static ColorPallete consolePallete = ColorPallete()
static bool colorPalleteInitialized = false
Additional Inherited Members
Public Types inherited from CursesWindow
typedef boost::shared_ptr< Window > window_ptr
Public Types inherited from Window
typedef boost::shared_ptr< Window > window_ptr
Protected Attributes inherited from CursesWindow
WINDOW * win
int y
int x
int height
int width
Detailed Description
ConsoleWindow.
Buffer and Curses window for a displaying in game log
Definition at line 16 of file ConsoleWindow.hpp.
Constructor & Destructor Documentation
ConsoleWindow::ConsoleWindow ()
Definition at line 6 of file ConsoleWindow.cpp.
References initColorPallete(), logger, and BufferLogger::setBufferCapacity().
ConsoleWindow::~ConsoleWindow () virtual
Definition at line 12 of file ConsoleWindow.cpp.
Member Function Documentation
BufferLogger * ConsoleWindow::getLogger ()
Definition at line 37 of file ConsoleWindow.cpp.
References logger.
void ConsoleWindow::initColorPallete () static private
Definition at line 47 of file ConsoleWindow.cpp.
References ColorPallete::addColor(), and colorPalleteInitialized.
Referenced by ConsoleWindow().
void ConsoleWindow::render () virtual
Reimplemented from CursesWindow.
Definition at line 17 of file ConsoleWindow.cpp.
References CursesWindow::clear(), BufferLogger::getBuffer(), BufferLogger::getBufferSize(), CursesWindow::getHeight(), CursesWindow::getWidth(), CursesWindow::height, logger, CursesWindow::putstr(), CursesWindow::render(), and CursesWindow::width.
void ConsoleWindow::setPallete () static
Definition at line 42 of file ConsoleWindow.cpp.
References ColorPallete::setCurrent().
Member Data Documentation
bool ConsoleWindow::colorPalleteInitialized = false static private
Definition at line 32 of file ConsoleWindow.hpp.
Referenced by initColorPallete().
ColorPallete ConsoleWindow::consolePallete = ColorPallete() static private
Definition at line 31 of file ConsoleWindow.hpp.
BufferLogger ConsoleWindow::logger private
Definition at line 30 of file ConsoleWindow.hpp.
Referenced by ConsoleWindow(), getLogger(), and render().
The documentation for this class was generated from the following files:
ConsoleWindow.hpp
ConsoleWindow.cpp