Trade App: game.cpp File Reference
game.cpp File Reference
#include <curses.h>
#include <iostream>
#include <signal.h>
#include <sstream>
#include <stdlib.h>
#include <string>
#include <time.h>
#include "Managers/Game.hpp"
Functions
static void finish (int sig)
int main ()
Function Documentation
static void finish (int sig) static
Definition at line 37 of file game.cpp.
Referenced by main().
 {
     endwin();
     exit(0);
 }
int main ()
Definition at line 14 of file game.cpp.
References finish(), Game::run(), and Game::setup().
 {
     srand(time(NULL));
     int num=0;
     signal(SIGINT, finish);
     initscr();
     keypad(stdscr, TRUE);
     cbreak();
     echo();
     if(has_colors()) {
         start_color();
     }
     Game myGame;
     myGame.setup();
     myGame.run();
     finish(0);
 }